### ISSUE TITLE
Web : การแสดงค่า รหัสสมาชิก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#10]
รหัสสมาชิก เป็น Running No. ที่ระบบกำหนดให้โดยอัตโนมัติ และเป็นตัวเชื่อมตารางข้อมูลต่างๆ ของสมาชิกเครือข่ายนั้นๆ

**Comment by cmmadnat** [comment]
รับทราบครับ จะกำหนดให้
