### ISSUE TITLE
Web :  การแสดงรายละเอียดข้อมูลสมาชิก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#11]
ในหน้านี้จะแสดงข้อมูลสมาชิกเท่านั้น แต่ให้มีปุ่มไปแสดงข้อมูลแปลงที่ดินได้
![image](https://user-images.githubusercontent.com/30930235/31130256-12860b80-a881-11e7-970c-f92b797e18ad.png)

**Comment by RDPB2-Kuer** [comment]
แต่ขอให้มีปุ่มจากหน้านี้ ไปดูส่วนที่เป็นแปลงที่ดินของสมาชิกคนนี้ได้เลยคะ จะมีปัญหากรณีถ้าสมาชิกคนนี้มีหลายแปลง ช่วยแนะนำหน่อยว่าจะให้เลือกอย่างไรดี

**Comment by cmmadnat** [comment]
กดที่ view ได้ครับ แต่เดี๋ยวอาจจะปรับ design
