### ISSUE TITLE
สมาชิก : หน้าแสดงรายการข้อมูล ระบบแสดงจำนวนหน้าก่อนรายการสมาชิก ซึ่งไม่ถูกต้อง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#116]
![image](https://user-images.githubusercontent.com/31124544/36085909-bd98d296-0ffb-11e8-939a-d128667833d8.png)

**Comment by RDPB2-Kuer** [comment]
OK
