### ISSUE TITLE
สมาชิก : หน้าเพิ่มและแก้ไขข้อมูลส่วนบุคคล ตรวจสอบการบันทึกข้อมูลเลขบัตรประชาชน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#118]
![image](https://user-images.githubusercontent.com/31124544/36087248-fa5a1ee4-1003-11e8-8cdd-aa0e67bc6f1b.png)

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
