### ISSUE TITLE
สมาชิก : หน้าเพิ่มข้อมูล Tab ข้อมูลส่วนบุคคล ไม่ต้องมีค่า Default ที่ระดับการศึกษา

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#128]
![image](https://user-images.githubusercontent.com/31124544/36088854-7d4f00c4-100b-11e8-8402-abba60aca6fb.png)

**Comment by RDPB2-Kuer** [comment]
OK
