### ISSUE TITLE
เปลี่ยนสี Icon เป็นโทนสีส้มด้วย

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#14]
น้องเล็กคะ รบกวนปรับสี Icon ตามภาพเป็นโทนสีส้มด้วยนะคะ
ไม่แน่ใจว่าแต่ละอันแต้องแยกกันหรือเปล่าเพราะพี่ไม่มีต้นฉบับ
น้องเล็กปรับสำหรับใช้บนแผนที่นะคะ
![image](https://user-images.githubusercontent.com/31124544/31164062-a4016788-a90f-11e7-9e6a-7a785be59e12.png)

@wannarukb

**Comment by RDPB2-Kuer** [comment]
เปลี่ยน IR ใหม่
