### ISSUE TITLE
สมาชิก : เพิ่มปุ่มลบที่หน้าแสดงรายการข้อมูล

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#145]
![image](https://user-images.githubusercontent.com/30930235/36143227-140bdab0-10dd-11e8-986b-0968bcf60d6d.png)

**Comment by anucha1892** [comment]
ขอปรับแก้ตามรูป ดังนี้
1. ปรับรูปถังขยะให้อยู่กึ่งกลางกรอบสีแดง
2. เปลี่ยนข้อความยืนยันการลบข้อมูล โดยใช้ตามรูปแบบนี้
![image](https://user-images.githubusercontent.com/33414080/36942644-889a5d30-1faa-11e8-8683-0a5f648c21b4.png)

**Comment by Srikridsadaporn** [comment]
ส่วนอื่นเรียบร้อยแต่ รบกวนปรับปุ่มตามรายละเอียดในภาพด้านล่าง
![image](https://user-images.githubusercontent.com/31124544/37010264-5304559e-211d-11e8-80e6-a50f6e907575.png)

**Comment by RDPB2-Kuer** [comment]
ปิดกรณีเพิ่มปุ่มแล้ว
