### ISSUE TITLE
สมาชิก :  หน้าเพิ่ม/แก้ไขข้อมูล  ตรวจสอบฟิลด์บังคับ และแจ้งเตือนถ้าไม่ใส่ข้อมูล

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#148]
![image](https://user-images.githubusercontent.com/31124544/36143973-36e8947c-10df-11e8-9d33-629e77b37eb1.png)

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
