### ISSUE TITLE
Web : การบันทึกข้อมูลที่สามารถระบุตัวเลือกหลายอัน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#15]
ในกรณีการบันทึกข้อมูลที่สามารถเลือก Drop down list ได้หลายอัน อยากให้แนตใช้แบบที่เคยทำใน กปร ระยะที่ 1 กรณีบันทึกหน่วยงานที่รับผิดชอบ เนื่องจากตัวเลือกทั้งหมดจะแสดงบนบรรทัดเดียวกัน แบบนี้
![screen shot 2560-10-04 at 15 54 40](https://user-images.githubusercontent.com/30930235/31167515-8a0934ac-a91c-11e7-8cb1-2619e98ec1a8.png)

**Comment by cmmadnat** [comment]
เพิ่มแล้วครับ สำหรับ specialty
![image](https://user-images.githubusercontent.com/37333/31181561-dd86ee2e-a94b-11e7-84e7-ffc4df08e969.png)

**Comment by RDPB2-Kuer** [comment]
ปิด
