### ISSUE TITLE
สมาชิก : หน้าเพิ่ม/แก้ไขข้อมูล ขอให้ปิดการแสดง Auto Fill

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#151]
![image](https://user-images.githubusercontent.com/30930235/36152481-cbace888-10fd-11e8-8d39-7d67988c053f.png)

**Comment by cmmadnat** [comment]
ตั้งปิดไว้เบื้องต้น แล้วแต่อาจจะปิดได้ไม่หมดครับ เพราะว่าหลังๆ browser เริ่มไม่เชื่อ https://stackoverflow.com/questions/2530/how-do-you-disable-browser-autocomplete-on-web-form-field-input-tag

**Comment by RDPB2-Kuer** [comment]
OK
