### ISSUE TITLE
สมาชิก : หน้าแสดงรายการข้อมูล ปรับปรุงการแสดงรายละเอียดย่อของสมาชิก #2

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#155]
มีบางส่วนแสดงผิด และขอปรับรูปแบบการแสดงผลอีกครั้ง ดังนี้

![image](https://user-images.githubusercontent.com/30930235/36237658-cc956c9c-122f-11e8-81a9-089779bd39a1.png)

**Comment by RDPB2-Kuer** [comment]
น้องเล็กคะ สามารถปรับให้ดีขึ้นได้เลยนะคะ พี่เชื่อการออกแบบของน้องเล็กคะ

**Comment by wannaruk-b** [comment]
ตอนนี้เป็นแบบนี้ค่ะ 
แบบเป็นสมาชิก
<img width="1199" alt="screen shot 2018-02-22 at 09 59 27" src="https://user-images.githubusercontent.com/28918051/36517979-249db57a-17b7-11e8-9e0f-80dda6ad735b.png">

แบบไม่เป็นสมาชิก
<img width="1207" alt="screen shot 2018-02-22 at 09 59 54" src="https://user-images.githubusercontent.com/28918051/36517994-39f34b2e-17b7-11e8-866c-33637e2f2b0a.png">

**Comment by RDPB2-Kuer** [comment]
เยี่ยมมากเลยคะ
