### ISSUE TITLE
สมาชิก : หน้าบันทึก/แก้ไขข้อมูล หลังกดปุ่มบันทึก พบว่าการแสดงผลข้อมูลเพศไม่ถูกต้อง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#157]
![image](https://user-images.githubusercontent.com/31124544/36185632-d3f56078-116c-11e8-9473-ae8d0ceeaa9e.png)

**Comment by RDPB2-Kuer** [comment]
OK
