### ISSUE TITLE
แปลงที่ดิน : หน้าบันทึก/แก้ไขข้อมูล ปรับปรุงหน้าบันทึก Tab ข้อมูลแปลงที่ดิน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#158]
ปรับปรุงการบันทึกรายละเอียดข้อมูลแปลงที่ดิน ดังนี้
![image](https://user-images.githubusercontent.com/30930235/36201464-9bb8874e-11b2-11e8-8d21-473bee9ecc05.png)

ส่วนด้านล่างเป็นหัวข้อย่อยต่อจากด้านบน ซึ่งจะเป็นงานของ Mapping แสดงให้ดูเพื่อให้เห็นว่าเป็นส่วนต่อเนื่องที่ต้องประสานกับ mapping ต่อไปด้วย
![image](https://user-images.githubusercontent.com/30930235/36193261-c89d4512-1197-11e8-91c3-464c9dcf2390.png)

**Comment by wannaruk-b** [comment]
ส่วนนี้ เรียบร้อยแล้วค่ะ จะเหลือแต่ จุดที่ใส่พิกัด อาจจะต้องรวมกับ iframe ของการใส่ค่าค่ะ

**Comment by RDPB2-Kuer** [comment]
ไม่เห็นตัวอย่างเลยคะ ขอดูตัวอย่างได้ไหมคะ

**Comment by wannarukb** [comment]
<img width="1190" alt="screen shot 2018-02-22 at 20 35 10" src="https://user-images.githubusercontent.com/23309321/36541261-edf8aef4-180f-11e8-9f3d-8ac9bad18e26.png">

ส่วนนี้น่าจะเป็นอีกหน้านึงเรื่องการ plot จุดนะคะ >__<
<img width="878" alt="screen shot 2018-02-22 at 20 36 25" src="https://user-images.githubusercontent.com/23309321/36541320-16e4d13a-1810-11e8-96e2-fb89f618f191.png">

**Comment by RDPB2-Kuer** [comment]
OK
