### ISSUE TITLE
Web : หน้าจอการบันทึกข้อมูลแปลงที่ดิน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#16]
ขอปรับแก้ดังนี้

![image](https://user-images.githubusercontent.com/30930235/31169959-92dc3388-a924-11e7-8fe2-4d5538d44897.png)

**Comment by RDPB2-Kuer** [comment]
การบันทึกข้อมูลส่วนนี้เป็น drop down list นะคะ
![screen shot 2560-10-04 at 16 55 03](https://user-images.githubusercontent.com/30930235/31170051-e36a497a-a924-11e7-85da-ff704eb6e819.png)

**Comment by RDPB2-Kuer** [comment]
การบันทึกข้อมูลส่วนนี้เป็น drop down list เช่นเดียวกัน
![screen shot 2560-10-04 at 16 56 18](https://user-images.githubusercontent.com/30930235/31170087-04a0897e-a925-11e7-9d23-4614c61cbee8.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/31181501-b3e8835c-a94b-11e7-93e4-e8f037ce6dca.png)
ปรับตามที่ขอแล้ว ยังขาดช่องบางส่วนที่ไม่มีข้อมูลอ้างอิง
เช่น ต้องการให้พื้นที่เป็น การถึือครองที่ดิน

**Comment by RDPB2-Kuer** [comment]
แก้ IR ใหม่
