### ISSUE TITLE
สมาชิก : หน้าค้นหาข้อมูล แสดงชื่อเล่นไม่ถูกต้อง

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#161]
![image](https://user-images.githubusercontent.com/31124544/36194742-898e479e-119d-11e8-82a9-8931d2bbb68f.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-02-28 at 15 53 41](https://user-images.githubusercontent.com/37333/36778532-9061e6cc-1c9f-11e8-81ad-ac1b2b327115.jpg)

**Comment by RDPB2-Kuer** [comment]
ข้อความ" ชื่อเล่น" ไม่ควรเน้นคะ ที่ควรเน้น คือข้อมูลชื่อเล่น อาจตัดหัวข้อ "ชื่อเล่น"  ออก แล้วแสดงข้อมูลชื่อเล่นแทน โดยใช้ขนาดตามหัวข้อชื่อเล่นเลยคะ

**Comment by RDPB2-Kuer** [comment]
OK
