### ISSUE TITLE
สมาชิก : เมนูหลัก ปรับแก้การแสดงเมนูหลัก ให้ย่อ/ขยาย ได้ 

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#162]
1. ปัจจุบัน
![image](https://user-images.githubusercontent.com/30930235/36237337-c4840678-122d-11e8-869c-2f208d64fdb5.png)

2. ที่ต้องการให้ปรับแก้ ดังนี้
![image](https://user-images.githubusercontent.com/30930235/36237391-f5806f8c-122d-11e8-856e-230243cbebf0.png)

3. และขอให้ปรับแก้การแสดงผลข้อมูลในแต่ละหน้าให้กว้างขึ้น ให้สอดคล้องกับเนื้อที่ที่เพิ่มขึ้น เช่นเดียวกับที่ทำ Prototype

**Comment by wannaruk-b** [comment]
เหมือนอันนี้จะมีให้ ย่อ/ขยายอยู่แล้วนะคะ
ไม่แน่ใจว่า กดแล้วได้หรือเปล่า >___<
แต่ โดย Default จะยืดออกก่อน แต่สามารถย่อเก็บได้ค่ะ
![1519208433348](https://user-images.githubusercontent.com/28918051/36474950-c3465cae-172b-11e8-95c8-66fdcc9b2bd8.jpg)

**Comment by RDPB2-Kuer** [comment]
อยากเพิ่มแบบที่ทำ Prototype นะคะ คือให้ยืดหดโดยอัตโนมัติ แต่ก็สามารถกดปุ่มที่บอกยืด/หดได้ 
ได้ไหมคะ

**Comment by wannarukb** [comment]
สามารถกด ได้เลยค่า ตามที่วงสีแดงไว้ฮะ

**Comment by RDPB2-Kuer** [comment]
OK
