### ISSUE TITLE
สมาชิก : หน้าบันทึก/แก้ไขข้อมูล ปรับแก้การแสดงหัวข้อย่อยใน Tab ให้ย่อ/ขยายได้

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#163]
ขอให้ปรับแก้ทุกๆ function ที่มีการแสดงหัวข้อย่อยแบบนี้

![image](https://user-images.githubusercontent.com/30930235/36237514-c8152794-122e-11e8-8595-fe119aa7bbfe.png)

**Comment by wannaruk-b** [comment]
เพิ่มให้เรียบร้อยแล้วค่า

<img width="1262" alt="screen shot 2018-02-21 at 20 13 42" src="https://user-images.githubusercontent.com/28918051/36481866-c2d41afa-1743-11e8-8ed5-bf583d9856ff.png">

**Comment by RDPB2-Kuer** [comment]
OK
