### ISSUE TITLE
แปลงที่ดิน : หน้าบันทึก/แก้ไข ปรับปรุงการออกแบบ นำเข้า/แก้ไข เมนูย่อย "รูปภาพประกอบ"

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#164]
![image](https://user-images.githubusercontent.com/30930235/36243001-cbe6b324-1251-11e8-9595-f21a903284c8.png)

**Comment by wannaruk-b** [comment]
เป็นแบบนี้นะคะ

<img width="1178" alt="screen shot 2018-02-22 at 18 53 35" src="https://user-images.githubusercontent.com/28918051/36537129-ce5e454e-1801-11e8-8c57-12dfabd6741d.png">

เมื่อกด เปรียบเทียบภาพถ่าย
จะขึ้นให้เลือกรูปภาพ
<img width="1158" alt="screen shot 2018-02-22 at 18 53 44" src="https://user-images.githubusercontent.com/28918051/36537141-dad3e180-1801-11e8-9303-79b0650ae638.png">

**Comment by RDPB2-Kuer** [comment]
ดีมากคะ

แต่อยากให้เพิ่มปุ่มสำหรับการนำเข้าข้อมูลด้วยได้ไหมคะ เหมือนกับข้อมูลสมาชิก
หรือแปลงที่ดิน ที่แสดงข้อมูลที่จัดเก็บก่อน แล้วต้องการปรับปรุงภาพถ่าย
ให้มีปุ่มให้กดเพิ่ม/แก้ไข/ลบ ภาพถ่าย เนื่องจาก
การเรียกดูข้อมูลแปลงที่ดินผ่านทาง Dashboard จะเป็นการดูอย่างเดียว
ปรับแก้ไม่ได้นะคะ

พอจะทำได้ไหมคะ
พี่กื้อ

2018-02-22 18:55 GMT+07:00 wannaruk-b <notifications@github.com>:

**Comment by wannaruk-b** [comment]
สามารถ กด icon สีส้มได้ค่ะ
<img width="843" alt="screen shot 2018-02-27 at 20 33 51" src="https://user-images.githubusercontent.com/28918051/36731506-952c1436-1bfd-11e8-9730-48e54a907486.png">

เมื่อกดแล้วจะมี Modal แสดงขึ้นมา ทำให้แก้ไขรูปภาพได้
<img width="927" alt="screen shot 2018-02-27 at 20 33 56" src="https://user-images.githubusercontent.com/28918051/36731516-9fca6758-1bfd-11e8-9cf2-e09eb2123543.png">

**Comment by RDPB2-Kuer** [comment]
OK
