### ISSUE TITLE
สมาชิก : หน้าเพิ่ม/แก้ไข กรณีกดปุ่มยกเลิก ให้แสดงหน้าข้อมูลสมาชิกก่อน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#166]
![image](https://user-images.githubusercontent.com/30930235/36781257-fa0d7be2-1ca7-11e8-8d5a-ade13f7515f0.png)

ระบบต้องแสดงหน้าล่างนี้ก่อน
![image](https://user-images.githubusercontent.com/30930235/36781457-7f69df24-1ca8-11e8-84a3-b9236ed0ea79.png)

**Comment by RDPB2-Kuer** [comment]
ให้แสดงที่หน้าจอ "ข้อมูลสมาชิก" ไม่ใช่ "รายงานสรุป"

**Comment by Srikridsadaporn** [comment]
เรียบร้อยค่ะ แต่หญิงปิดไม่ได้

**Comment by RDPB2-Kuer** [comment]
OK
