### ISSUE TITLE
สมาชิก :  การเพิ่ม/แก้ไขข้อมูล ปรับช่องบันทึกข้อมูล text & Drop down list ให้เหมือนกัน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#168]
![image](https://user-images.githubusercontent.com/30930235/36788933-66c0c2ca-1cc2-11e8-9e29-97b450bf069b.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-03-02 at 01 26 30](https://user-images.githubusercontent.com/37333/36862221-c213aaba-1db8-11e8-8b5d-475de62b8af2.jpg)
ผมว่าของจางกว่าสวยกว่า ทดลองดูก่อนครับ

**Comment by RDPB2-Kuer** [comment]
OK
