### ISSUE TITLE
สมาชิก : หน้าค้นหาข้อมูล ปรับรูปแบบการแสดงเบอร์โทรศัพท์

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/itok#174]
รายละเอียดตามภาพครับ
![image](https://user-images.githubusercontent.com/33414080/36881395-74ddf000-1e00-11e8-9a2e-c85f6426f70a.png)

**Comment by RDPB2-Kuer** [comment]
การกรอก และจัดเก็บ เป็นแบบเดิม แต่ให้การแสดงผลข้อมูลให้มี "-" คั่น

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย
