### ISSUE TITLE
สมาชิก : หน้าค้นหา - ปรับแก้การแสดงข้อมูลสถานะสมาชิก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#175]
1. การแสดงหน้าจอค้นหา ปัจจุบัน แสดงข้อมูลสถานะสมาชิก ไม่ถูกต้อง 

2. ขอให้ปรับปรุงให้มีขนาดของแถบสี และสี ตามที่น้องเล็กออกแบบไว้ (หดแถบให้สั้นลง)

3. กรณีเป็นสมาชิก
![image](https://user-images.githubusercontent.com/30930235/36887254-e895ff16-1e22-11e8-9735-96c5e83173e2.png)

4. กรณี ยังไม่เป็นสมาชิก 
![image](https://user-images.githubusercontent.com/30930235/36887209-afe79bac-1e22-11e8-8a2a-059d481c136f.png)

**Comment by Srikridsadaporn** [comment]
ปรับแก้แล้วค่ะ แต่ทำไมมันดูไม่ค่อยสมดุล

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
