### ISSUE TITLE
สมาชิก : หน้าแสดงข้อมูล - แสดงชื่อไม่ตรงกับหน้าค้นหาข้อมูลสมาชิก

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/itok#176]
รายละเอียดตามภาพด้านล่าง
![image](https://user-images.githubusercontent.com/33414080/36887446-dc1e91b6-1e23-11e8-8d8a-37678b479880.png)

**Comment by RDPB2-Kuer** [comment]
เกิดขึ้นในกรณีที่ รหัสไปรษณีย์ ในข้อมูลที่อยู่ ไม่มีอยู่ในระบบ
