### ISSUE TITLE
สมาชิก : หน้าแก้ไข - ปรับปรุงลำดับการแสดงหน้าจอหลังกดปุ่มบันทึก 

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#178]
1. กรณีแก้ไข เมื่อกดปุ่ม "บันทึก: ให้แสดง background ดังภาพด้านล่าง จนกว่าจะกดปุ่ม OK
![screen shot 2561-03-02 at 14 42 57](https://user-images.githubusercontent.com/30930235/36888484-4389ed56-1e28-11e8-911a-5f09cd7eaa93.png)

2. และเมื่อกดปุ่ม OK ให้แสดงที่หน้า "ข้อมูลสมาชิก" ไม่ใช่ "รายงานสรุป"
![image](https://user-images.githubusercontent.com/30930235/36888624-e1bad68e-1e28-11e8-9ee8-15d97f6cddb3.png)

3. ในกรณีที่กดปุ่ม "ยกเลิก" ให้แสดงที่หน้า "ข้อมูลสมาชิก" ไม่ใช่ "รายงานสรุป" เช่นกัน

**Comment by Srikridsadaporn** [comment]
เรียบร้อยค่ะ  แต่หญิงปิดไม่ได้

**Comment by RDPB2-Kuer** [comment]
OK
