### ISSUE TITLE
สมาชิก : หน้าเพิ่ม/แก้ไข - ปรับปรุงการแจ้งเตือนกรณีกรอกข้อมูลไม่ถูกต้อง และไม่ใส่ข้อมูลบังคับให้เหมือน กปร

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#179]
![image](https://user-images.githubusercontent.com/31124544/36888961-65d67512-1e2a-11e8-92c0-59442c2a700e.png)

![image](https://user-images.githubusercontent.com/31124544/36888870-fc8bb3ba-1e29-11e8-9828-2e35bbe06d74.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/36943769-6e2f2e3c-1fc1-11e8-9db0-06a9fe15ad58.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/36943786-ce2befe6-1fc1-11e8-8084-59e73a0a526e.png)

**Comment by Srikridsadaporn** [comment]
OK
