### ISSUE TITLE
สมาชิก- หน้าเพิ่ม ลดขนาด Font การแจ้งเตือนให้ขนาดเท่ากับที่ใช้ใน กปร.

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#181]
![image](https://user-images.githubusercontent.com/31124544/36889832-46303b04-1e2e-11e8-81dc-866ee255a7fb.png)

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
