### ISSUE TITLE
สมาชิก : หน้าแก้ไขสมาชิก ปรับแก้การแสดงกรณี "เปลี่ยนรูปถ่ายสมาชิก"

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/itok#184]
ในกรณีเปลี่ยนรูปถ่ายสมาชิก ขอให้ปรับการแสดงรูปให้เป็นมาตรฐานเดียวกัน
อธิบายจากรูป ดังนี้
1. รูปถ่ายสมาชิก จะอยู่กึ่งกลางกรอบสีเทา จากนั้นกดปุ่ม "เปลี่ยนรูป"  
2. เมื่อเลือกเปลี่ยนรูปแล้ว รูปถ่ายสมาชิก จะแสดงชิดซ้าย ขอให้ปรับการแสดงรูปให้อยู่กึ่งกลางให้เหมือนกับรูปที่ 1
![image](https://user-images.githubusercontent.com/33414080/36891162-2f3b4d08-1e33-11e8-83c2-fd62c9bec5a8.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/36943633-fd68e74e-1fbe-11e8-9d17-19788fda8bfc.png)

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย
