### ISSUE TITLE
สมาชิก : หน้าเพิ่ม/แก้ไขสมาชิกเครือข่าย ปรับรูปแบบการเลือก "วันเกิด"

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/itok#185]
จากรูป ขอให้ปรับการเลือกวันเกิด ให้เลือกตาม วัน/เดือน/ปี(พ.ศ.) ตามรูปแบบนี้
![image](https://user-images.githubusercontent.com/33414080/36891880-941a885e-1e35-11e8-9f9d-b4c94c2acf84.png)

**Comment by RDPB2-Kuer** [comment]
ปรับแก้ใหม่ แบบเดิม ให้ใส่ พ.ศ. ได้แล้ว
