### ISSUE TITLE
สมาชิก : หน้าแก้ไขข้อมูลสมาชิก ปรับปรุงการใส่ข้อมูลที่อยู่ของระบบ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#193]
![image](https://user-images.githubusercontent.com/31124544/36969010-d28bbd70-2096-11e8-8f8f-9784f275f5be.png)

**Comment by cmmadnat** [comment]
ไม่เป็นนะครับ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย  ขอบคุณค่ะ
