### ISSUE TITLE
สมาชิก : หน้าบันทึก/แก้ไข - ปรับแก้ข้อความแจ้งเตือนเบอร์มือถือ และแก้ปัญหาบันทึกข้อมูลไม่ได้

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#195]
![image](https://user-images.githubusercontent.com/30930235/37011445-d1b1fa40-2122-11e8-84f9-b9c89a9eaee0.png)

และเมื่อใส่ข้อมูลต่อโดยยังไม่ย้าย field ให้ลบการแจ้งเตือนออก

![image](https://user-images.githubusercontent.com/30930235/37011517-290864fa-2123-11e8-8a6c-5b929e0c8b79.png)

**Comment by cmmadnat** [comment]
เช่นเดียวกับ #197  ครับ อาจจะแก้ไขไม่ได้ เป็นส่วนของ plugin

**Comment by RDPB2-Kuer** [comment]
OK
