### ISSUE TITLE
สมาชิก : หน้าเพิ่ม/แก้ไข - การกรอกข้อมูลวันเกิด ระบบแสดงข้อมูลไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#196]
![image](https://user-images.githubusercontent.com/30930235/37011814-64767d46-2124-11e8-9da4-56fd5a9609ff.png)

เมื่อกรอกเสร็จ ระบบแสดงเป็นค่าที่ไม่ได้บันทึก
![image](https://user-images.githubusercontent.com/30930235/37011868-9ec76500-2124-11e8-8440-7d733c20228c.png)

**Comment by Srikridsadaporn** [comment]
ปรับแล้ว ส่วน พ.ศ. ตอนนี้ยังไม่ค่อยสะดวกต่อการใช้ คือต้องพิมพ์ใหม่เอง เพราะถ้าใช้วิธีเลือก การคลิกเมาส์ 1 ครั้งเท่ากับขยับเลื่อน 1 เดือน

**Comment by RDPB2-Kuer** [comment]
ต้องใส่ / ด้วย
