### ISSUE TITLE
สมาชิก : หน้าบันทึก/แก้ไข - ปรับแก้ข้อความแจ้งเตือนบัตรประชาชน และแก้ปัญหาบันทึกข้อมูลไม่ได้

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#197]
![image](https://user-images.githubusercontent.com/30930235/37012006-1a8e09e6-2125-11e8-9f5f-922d6597e4e2.png)

กำลังแก้ไข ยังไม่ย้าย field ไม่ต้องแจ้งเตือน
![image](https://user-images.githubusercontent.com/30930235/37012194-035b0002-2126-11e8-9128-16ec45645f18.png)

**Comment by cmmadnat** [comment]
ไม่แน่ใจว่าสามารถปรับได้ไหมนะครับ

**Comment by RDPB2-Kuer** [comment]
OK
