### ISSUE TITLE
สมาชิก: หน้าค้นหาข้อมูลสมาชิก ผลลัพธ์ยังไม่ตรงตามเงื่อนไข

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#198]
1. การค้นหาสำหรับเงื่อนไข "ชื่อ" รายละเอียดตามภาพด้านล่างนี้
2. การค้นหาด้วยเบอร์โทรศํพท์ ควรจะสามารถใช้แค่บางส่วนของข้อมูลได้ด้วย ไม่จำเป็นต้องใส่เบอร์โทรครบทั้ง 10 ตัว เช่น อาจค้นหาด้วยการใส่เป็น "086" ก็แสดงผลเบอร์โทรที่มีเลขนี้อยู่

![image](https://user-images.githubusercontent.com/31124544/37012220-41ef1a38-2126-11e8-8cb8-a8e041eefdf8.png)

**Comment by cmmadnat** [comment]
เป็นส่วนของ Search Engine ครับ เราเข้าไปยุ่งกับการตัดคำไทยของระบบกลางไม่ได้

**Comment by Srikridsadaporn** [comment]
เรียบร้อย  ขอบคุณ
