### ISSUE TITLE
Web : ปรับแก้ Main Menu

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#2]

**Comment by RDPB2-Kuer** [comment]
ปรับปรุงใหม่ ดังนี้
![image](https://user-images.githubusercontent.com/30930235/31063698-94faa0c6-a75f-11e7-8f6b-f2fe882ca720.png)

**Comment by RDPB2-Kuer** [comment]
หากมีรูปสัญญลักษณ์ที่หน้าหัวข้องด้วย จะดีมากเลยคะ

**Comment by RDPB2-Kuer** [comment]
ช่วยเปิดให้พี่แก้ Label ด้วยนะคะ

**Comment by RDPB2-Kuer** [comment]
ลืมไปขอปรับปรุง menu เพิ่มเติม ดังนี้
6. อุปกรณ์ในโครงการ 
7. ผู้ใช้งาน

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/31081095-e6fa93cc-a7b4-11e7-9234-351053e30050.png)

**Comment by RDPB2-Kuer** [comment]
ขอเปลี่ยน icon สมาชิกเครือข่าย เป็นอันนี้นะคะ
![image](https://user-images.githubusercontent.com/30930235/31128070-d8f02794-a87a-11e7-9a62-62cac027acaa.png)

**Comment by RDPB2-Kuer** [comment]
![image](https://user-images.githubusercontent.com/30930235/31128385-d40fc634-a87b-11e7-953e-a321735944a6.png)

**Comment by RDPB2-Kuer** [comment]
จะได้แตกต่างกับผู้ใช้งาน

**Comment by RDPB2-Kuer** [comment]
ขอให้มีรูปหน้าและชื่อคน Login แสดงบนแถบเมนูด้วยนะคะ ถ้าไม่ให้ใช้รูป Default
