### ISSUE TITLE
สมาชิก : หน้าค้นหา - กรณีกดที่ชื่อให้แสดงข้อมูลแปลงที่ดิน ไม่ใช่ข้อมูลสมาชิก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#203]
![image](https://user-images.githubusercontent.com/30930235/37025940-93ad9aa0-215f-11e8-97ae-e8321c833fa5.png)

**Comment by cmmadnat** [comment]
ไม่เข้าใจครับว่าควรจะเป็นแบบไหน

**Comment by RDPB2-Kuer** [comment]
OK
