### ISSUE TITLE
สมาชิก : หน้าค้นหา จำนวนหน้าที่แสดงมากกว่าผลลัพธ์ และแสดง Error เมื่อเลือกหน้าอื่นๆ

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#204]
![image](https://user-images.githubusercontent.com/31124544/37026086-f1b932da-215f-11e8-99ac-32257b8ce128.png)

**Comment by cmmadnat** [comment]
ไม่เห็นเป็นเลยครับ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
