### ISSUE TITLE
แปลงที่ดิน : หน้าเพิ่มแปลงที่ดิน ตรวจสอบค่า สูงสุดของหน่วย "งาน" และ "ตร.วา"

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#207]
![image](https://user-images.githubusercontent.com/31124544/37079969-2a33f246-2217-11e8-844c-e56a17ef97d5.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-03-09 at 10 09 14](https://user-images.githubusercontent.com/37333/37188482-f48652c6-2381-11e8-9fcc-6d477cb3f828.jpg)

**Comment by Srikridsadaporn** [comment]
![image](https://user-images.githubusercontent.com/31124544/37194374-7eec5ffa-23a0-11e8-9995-31d1296a0754.png)

**Comment by anucha1892** [comment]
แก้ไขเรีียบร้อย

**Comment by Srikridsadaporn** [comment]
เรีียบร้อย...ขอบคุณค่ะ
