### ISSUE TITLE
แปลงที่ดิน :  หน้าเพิ่มแปลง ปรับปรุงรูปแบบหน้าจอและการใช้งาน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#209]
![image](https://user-images.githubusercontent.com/31124544/37202271-a16c0b0e-23bc-11e8-8afb-d8bcc4b45841.png)

**Comment by cmmadnat** [comment]
ผมขอลองแก้เป็นการใส่ modal ขนาด เต็มจอในส่วนของโจ้นะครับ เพราะว่าส่วนนี้ถ้าเป็นแท็บอีกอันหนึ่งมันจะกว้างเท่าเดิมอยู่ดี

**Comment by cmmadnat** [comment]
ทดลองดูก่อนครับ

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย

**Comment by Srikridsadaporn** [comment]
![image](https://user-images.githubusercontent.com/31124544/37252127-7b59a5f0-254e-11e8-841b-90ad68ec7639.png)

**Comment by Srikridsadaporn** [comment]
ปิดและเปิดใหม่เป็น 221
