### ISSUE TITLE
แปลงที่ดิน : หน้ารูปภาพประกอบ ปรับแก้การนำเข้ารูปภาพ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#210]
น้องเล็กออกแบบให้ใหม่ เป็นแบบนี้

1. สามารถกดที่ปุ่ม สีส้ม
![image](https://user-images.githubusercontent.com/30930235/37084887-3fab188e-2226-11e8-94bb-71dffd68ea1d.png)
 
2. เมื่อกดแล้วจะมี Modal แสดงขึ้นมา ทำให้แก้ไขรูปภาพได้
![image](https://user-images.githubusercontent.com/30930235/37084658-b3261d00-2225-11e8-8b5a-917ea3fe9587.png)

**Comment by cmmadnat** [comment]
หมายถึงให้ปรับ design หรือว่าแบบไหนครับ

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
