### ISSUE TITLE
เมนูหลัก :  เปลี่ยนรูป icon "แปลงที่ดิน"

### ISSUE THREAD

**Issue by juthamardden** [cmmadnat/itok#211]
แก้ไขตามภาพด้านล่างค่ะ
![default](https://user-images.githubusercontent.com/37205610/37198245-45ba8f08-23b0-11e8-8add-c75bb600e3e3.png)

![image](https://user-images.githubusercontent.com/30930235/37210915-e3e4efb2-23dc-11e8-9932-51172d2ee9d1.png)

**Comment by cmmadnat** [comment]
ไอค่อนอันนี้เอามาจากไหนเหรอครับ

**Comment by anucha1892** [comment]
แก้ไขเรีียบร้อย
