### ISSUE TITLE
แปลงที่ดิน : หน้าค้นหาแปลงที่ดิน ปรับแก้การแสดงผล ไร่-งาน-ตร.วา

### ISSUE THREAD

**Issue by juthamardden** [cmmadnat/itok#212]
ปรับแก้ดังภาพด้านล่าง ดังนี้
![image](https://user-images.githubusercontent.com/37205610/37198991-c8d7ba80-23b2-11e8-8d11-a1713b922922.png)

**Comment by anucha1892** [comment]
แก้ไขตรงส่วนนี้ด้วยนะครับ
![image](https://user-images.githubusercontent.com/33414080/37249298-9a0b7b0e-2517-11e8-96bd-64f19a4e20b0.png)

**Comment by juthamardden** [comment]
แก้ไขเรียบร้อย

![image](https://user-images.githubusercontent.com/37205610/37275752-a2b90e14-2612-11e8-8a0c-027b31714e58.png)
