### ISSUE TITLE
แปลงที่ดิน : หน้าเพิ่มแปลง ปรับปรุงรูปแบบหน้าจอและการใช้งาน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#213]
![image](https://user-images.githubusercontent.com/31124544/37202748-fc98b49a-23bd-11e8-8f9a-e910fe787464.png)

**Comment by anucha1892** [comment]
ซ้ำกับข้อ 209

**Comment by Srikridsadaporn** [comment]
ขอบคุณค่ะ
