### ISSUE TITLE
สมาชิก : ขั้นตอนการเพิ่มสมาชิกใหม่

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#214]
![image](https://user-images.githubusercontent.com/31124544/37203750-4c255ede-23c1-11e8-8460-353331524068.png)

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย

**Comment by Srikridsadaporn** [comment]
เรีียบร้อย...ขอบคุณค่ะ
