### ISSUE TITLE
สมาชิก : หน้าเพิ่ม/แก้ไข - ระบบทำงานไม่ถูกต้องเมื่อกดปุ่ม บันทึก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#217]
เมื่อแก้ไขแล้วกดปุ่ม "บันทึก" 
1. ระบบแสดงห้ามบันทึกแป๊บเดียว ซึ่งไม่ถูกต้อง
2. ระบบไม่แจ้งเตือนว่า บันทึกเรียบร้อยแล้ว ซึ่งไม่ถูกต้อง
3. ระบบอยู่ที่หน้าจอที่บันทึกเช่นเดิม ซึ่งไม่ถูกต้อง
4. ต้องกดปุ่มยกเลิก หน้าจอไปแสดงที่หน้าคั่น ซึ่งไม่ถูกต้อง
5. ข้อมูลที่แสดงที่หน้าคั่น ก็แสดงเป็นข้อมูลที่แก้ไขแล้ว ซึ่งไม่ถูกต้อง

ที่ถูกต้อง คือ เมื่อแก้ไขแล้วกดปุ่มบันทึก ต้องแสดงหน้าจอแจ้งเตือนว่า บันทึกเรียบร้อยแล้ว เมื่อกดปุ่ม OK ระบบจะแสดงที่หน้าคั่น
![image](https://user-images.githubusercontent.com/30930235/37210638-0c08ec06-23dc-11e8-9986-78be65a127fc.png)

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย

**Comment by RDPB2-Kuer** [comment]
OK
