### ISSUE TITLE
แปลงที่ดิน : หน้าคั่น -  ปรับปรุงการแสดงผลข้อมูลให้สอดคล้องกับหน้าบันทึก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#218]
ปรับปรุงหน้าจอเดิมเป็นหน้าจอใหม่ ดังนี้

![image](https://user-images.githubusercontent.com/30930235/37213401-804ea134-23e4-11e8-885c-92b7fa3fe82b.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/37244136-f8a0c6f8-24b6-11e8-9122-186af574b40d.png)

**Comment by Srikridsadaporn** [comment]
เรียบร้อยค่ะ
