### ISSUE TITLE
Dashboard - สมาชิก : หน้าค้นหา ย้ายปุ่มกลับ dashboard ให้ตรงกับปุ่มค้นหา

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#226]
![image](https://user-images.githubusercontent.com/30930235/37342432-22c30198-26f7-11e8-9ea7-f5eb2def996c.png)

**Comment by cmmadnat** [comment]
ตาม #226

**Comment by RDPB2-Kuer** [comment]
OK
