### ISSUE TITLE
Dashboard - แปลงที่ดิน :หน้าค้นหา ย้ายปุ่มกลับ dashboard ให้ตรงกับปุ่มค้นหา

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#227]
![image](https://user-images.githubusercontent.com/30930235/37342692-e8cd6d4c-26f7-11e8-92f2-6250a04e1f08.png)

**Comment by cmmadnat** [comment]
ปุ่ม dashboard ตรงกับหน้ารายงานอื่นๆ ครับ

**Comment by RDPB2-Kuer** [comment]
OK
