### ISSUE TITLE
สมาชิก : หน้าค้นหา ปรับปรุงการแสดงจำนวนแปลงที่ดินให้ครบตามจำนวน

### ISSUE THREAD

**Issue by juthamardden** [cmmadnat/itok#249]
จากภาพ นภา เย็นเอี่ยม มีแปลงที่ดินทั้งหมด 2 แปลง แต่ระบบฯแสดงแค่ 1 แปลง

![messageimage_1521096255155](https://user-images.githubusercontent.com/37205610/37448050-44369a7c-2857-11e8-8e45-828a35f70674.jpg)

**Comment by cmmadnat** [comment]
![screen shot 2561-03-15 at 14 12 55](https://user-images.githubusercontent.com/37333/37448941-0161bf02-285b-11e8-9d30-b6fb94773da9.jpg)
