### ISSUE TITLE
สมาชิก : หน้าคั่น เปิด TAB "แปลงที่ดิน" และทำให้ ปุ่ม "เพิ่มแปลงที่ดิน" และ "ดูข้อมูลแปลงที่ดิน" ใช้งานได้

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#250]
![image](https://user-images.githubusercontent.com/31124544/37457922-f0a7fa80-2875-11e8-8452-5256fd10cd60.png)

**Comment by anucha1892** [comment]
ปุ่ม "เพิ่มแปลงที่ดิน" ใช้งานได้แล้ว แต่ปุ่ม "ดูข้อมูลแปลงที่ดิน" ยังใช้งานไม่ได้ครับ

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย พี่หญิงปิดให้ด้วยนะครับ

**Comment by Srikridsadaporn** [comment]
OK

2018-03-21 15:40 GMT+07:00 anucha1892 <notifications@github.com>:

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
