### ISSUE TITLE
สมาชิก : หน้าคั่น ปรับแก้การแสดงวันที่บันทึกข้อมูลผิด

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#251]
![image](https://user-images.githubusercontent.com/31124544/37515878-d8fa137c-293e-11e8-9c76-18f98166abb1.png)

**Comment by cmmadnat** [comment]
![screen shot 2561-03-20 at 13 27 22](https://user-images.githubusercontent.com/37333/37639040-700d40da-2c42-11e8-9af8-c3722acf33aa.jpg)

**Comment by RDPB2-Kuer** [comment]
OK
