### ISSUE TITLE
Dashbord : หน้าแผนที่ ขยายให้แสดงประเทศไทยครบทุกส่วน

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#252]
![image](https://user-images.githubusercontent.com/31124544/37588969-6d5bbfc6-2b96-11e8-9e27-31b18c299deb.png)

**Comment by cmmadnat** [comment]
ย้ายมาไว้ด้านบน
![screen shot 2561-03-20 at 13 06 54](https://user-images.githubusercontent.com/37333/37638456-9839f47a-2c3f-11e8-8893-d377a294c244.jpg)

**Comment by RDPB2-Kuer** [comment]
ขอให้เป็นรูปประเทศได้เต็มๆ นะคะ

**Comment by Srikridsadaporn** [comment]
เรียบร้อย...ขอบคุณค่ะ
