### ISSUE TITLE
แปลงที่ดิน : หน้าค้นหา - ค้นหาจาก "ที่อยู่" ระบบไม่แสดงข้อมูลที่ค้นพบ

### ISSUE THREAD

**Issue by anucha1892** [cmmadnat/itok#256]
รูปที่ 1 เป็นรายการที่แสดงก่อนการค้นหา
รูปที่ 2 ใส่คำค้นหาจากที่อยู่ "กำแพงเพชร" ระบบไม่แสดงรายการที่ค้นพบ 
![image](https://user-images.githubusercontent.com/33414080/37760226-a441ee08-2de8-11e8-9388-5e4ea6b54a5d.png)

**Comment by anucha1892** [comment]
"ที่อยู่" ลองทดสอบใส่ชื่อจังหวัด บางจังหวัดก็แสดงรายการที่ค้นหา บางจังหวัดก็ไม่แสดงรายการ แนตลองหาสาเหตุและปรับแก้ให้ถูกต้องด้วยนะครับ

**Comment by RDPB2-Kuer** [comment]
ระบุค้นหาโดยใส่ "กำแพงเพชร" หาไม่พบ
![image](https://user-images.githubusercontent.com/30930235/37883430-81960c2e-30d4-11e8-983b-90485707fbb3.png)

**Comment by anucha1892** [comment]
แก้ไขเรียบร้อย
