### ISSUE TITLE
Prototype : หน้าจอแปลงที่ดิน - ปรับปรุง Default รูปภาพแปลงที่ดิน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#28]
จะเปลี่ยนรูป Default แปลงที่ดิน หรือ Default สมาชิกเครือข่าย ก็ได้ แต่ขอให้สอดคล้องกัน คือ ขอให้เป็นรูปภาพ หรือ ภาพวาด แบบใดแบบหนึ่ง

![image](https://user-images.githubusercontent.com/30930235/32477485-2b0d10d6-c3b1-11e7-9815-5622a1735727.png)

**Comment by wannarukb** [comment]
อันนี้รูป Default ที่ดินคือ อยากให้เป็นไอคอนมากแบบรูป default สมาชิกใช่มั้ยคะ ? >_<

**Comment by RDPB2-Kuer** [comment]
ใช่ค่ะ

**Comment by RDPB2-Kuer** [comment]
OK
