### ISSUE TITLE
Prototype : หน้าจอแปลงที่ดิน - ปรับแก้หน้าจอแสดงรายการ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#29]
![image](https://user-images.githubusercontent.com/30930235/32976698-540c48a2-cc4f-11e7-952a-37490456e68c.png)

**Comment by wannarukb** [comment]
เดี๋ยวอันนี้เล็กขอรวม เพื่อปรับหน้านี้ใหม่ทั้งหมดเลยนะคะ

**Comment by RDPB2-Kuer** [comment]
ได้ค่ะ

**Comment by RDPB2-Kuer** [comment]
น้องเล็กค่ะ ตรงที่ list รายการแปลงที่ดิน จะแสดงชื่อสมาชิกเจ้าของแปลงด้วยดีไหมคะ
เพื่อให้กรณีที่ user เลือกที่ แปลงที่ดิน จะได้ใช้การแสดงรายการแปลงที่ดินแบบเดียวกันเลย

**Comment by RDPB2-Kuer** [comment]
OK
