### ISSUE TITLE
Prototype : ปรับแก้หน้าจอแสดงรายการแปลงที่ดิน (บรรทัดที่ 2)

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#30]
![image](https://user-images.githubusercontent.com/30930235/32478558-0be4ca4e-c3b8-11e7-89be-7c9d7de465e7.png)

**Comment by wannarukb** [comment]
เดี๋ยวอันนี้เล็กขอรวม เพื่อปรับหน้านี้ใหม่ทั้งหมดเลยนะคะ

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
