### ISSUE TITLE
Prototype : หน้าจอสมาชิก - ปรับแก้การแสดงหัวข้อในรายงานสรุป

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#31]
![image](https://user-images.githubusercontent.com/30930235/32478877-99d2a668-c3b9-11e7-8492-0c4f37584426.png)

**Comment by wannarukb** [comment]
เรียบร้อยค่ะ
<img width="1139" alt="screen shot 2017-11-17 at 01 53 01" src="https://user-images.githubusercontent.com/23309321/32909795-152aba94-cb3a-11e7-83b0-7883902ec921.png">

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
