### ISSUE TITLE
Prototype : หน้าจอสมาชิก - ปรับแก้หัวข้อบนเมนูย่อย

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#32]
![image](https://user-images.githubusercontent.com/30930235/32499598-997f0b24-c405-11e7-9a6b-1e0ad64ca3d9.png)

**Comment by wannarukb** [comment]
ปรับเรียบร้อยแล้วค่ะ
<img width="619" alt="screen shot 2017-11-17 at 01 30 11" src="https://user-images.githubusercontent.com/23309321/32908694-e4c57536-cb36-11e7-8594-7ca2bf3d9a73.png">

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
