### ISSUE TITLE
Prototype : ปรับแก้หน้าจอสมาชิก (Tab 2)

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#33]
![image](https://user-images.githubusercontent.com/30930235/32480397-41cb54da-c3c1-11e7-9a17-f01eea66b062.png)

**Comment by wannarukb** [comment]
เรียบร้อยค่ะ
<img width="890" alt="screen shot 2017-11-17 at 01 45 46" src="https://user-images.githubusercontent.com/23309321/32909357-0ffd7440-cb39-11e7-9692-64ecb16a7a5d.png">

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
