### ISSUE TITLE
Prototype : ปรับปรุงหน้าจอสมาชิก (ใส่รูปตัวอย่าง)

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#34]
![image](https://user-images.githubusercontent.com/30930235/32480473-a2d2068e-c3c1-11e7-9791-73cf7a695f32.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
<img width="408" alt="screen shot 2017-11-18 at 16 58 01" src="https://user-images.githubusercontent.com/23309321/32979109-a8bd30dc-cc81-11e7-97ae-88d3648f83ab.png">

**Comment by RDPB2-Kuer** [comment]
OK
