### ISSUE TITLE
Prototype : ปรับแก้หน้าจอสมาชิก (รายงานสรุป-ส่วนที่ 2)

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#35]
![image](https://user-images.githubusercontent.com/30930235/32481741-4c8d6cd6-c3c7-11e7-93d4-f02abf23b8a9.png)

**Comment by wannarukb** [comment]
เรียบร้อยค่ะ
<img width="433" alt="screen shot 2017-11-17 at 01 50 13" src="https://user-images.githubusercontent.com/23309321/32909648-aebafbde-cb39-11e7-85f4-6bd7382b229f.png">

**Comment by RDPB2-Kuer** [comment]
แก้ไขเรียบร้อย
