### ISSUE TITLE
Prototype : ออกแบบหน้าจอ Login

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#36]
![image](https://user-images.githubusercontent.com/30930235/32485134-dfc6600e-c3d4-11e7-958b-1b8125ae0ab4.png)

Logo ของ ITOK
![logo-itok](https://user-images.githubusercontent.com/30930235/32485160-02f89fba-c3d5-11e7-8ad3-66a348f60796.jpg)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ

<img width="1280" alt="screen shot 2017-11-19 at 19 33 14" src="https://user-images.githubusercontent.com/23309321/32990699-881ea3da-cd60-11e7-9a54-f457ae188584.png">

**Comment by RDPB2-Kuer** [comment]
OK
