### ISSUE TITLE
Prototype : ปรับแก้หน้าจอ Main Menu

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#37]
ปรับแก้หน้าจอ Menu ดังนี้

![image](https://user-images.githubusercontent.com/30930235/32487275-c897ba3e-c3db-11e7-99f1-0c05e1f049bc.png)

**Comment by wannarukb** [comment]
เรียบร้อยค่ะ ขออนุญาตเป็นแบบนี้นะคะ
<img width="412" alt="screen shot 2017-11-18 at 17 32 04" src="https://user-images.githubusercontent.com/23309321/32979365-710eddb6-cc86-11e7-8484-cefbb231921e.png">

**Comment by RDPB2-Kuer** [comment]
ยอดเยี่ยมเลยคะ น้องเล็ก

**Comment by RDPB2-Kuer** [comment]
OK
