### ISSUE TITLE
Prototype : ปรับปรุงหน้าจอแสดงรายการแปลงที่ดินให้เป็นรูปแบบเดียวกัน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#38]
![image](https://user-images.githubusercontent.com/30930235/32496406-a9401440-c3fb-11e7-9c50-5ff26dd47812.png)

![image](https://user-images.githubusercontent.com/30930235/32496426-bec96d48-c3fb-11e7-9e76-cc4c3e35bf89.png)

และขอให้เพิ่มการแสดงรายการแปลงที่ดิน เมื่อเลือก Function "แปลงที่ดิน" จาก Main Menu

**Comment by wannarukb** [comment]
แก้เรียบร้อยแล้วค่ะ

**Comment by RDPB2-Kuer** [comment]
คือไม่ควรมี action  อยู่ด้านหน้านะคะ ทำเหมือนสมาชิก ได้ไหมค่ะ อยู่ด้านหลัง

**Comment by RDPB2-Kuer** [comment]
การแสดงรายการแปลงที่ดินขอเป็นรูปแบบนี้นะคะ
![image](https://user-images.githubusercontent.com/30930235/33108033-9cfb4458-cf6c-11e7-9a8c-4fc83cbb44ed.png)

**Comment by wannarukb** [comment]
ขอรวมไว้กับ #41 
<img width="1108" alt="screen shot 2017-11-22 at 23 23 06" src="https://user-images.githubusercontent.com/23309321/33138076-33bd2a54-cfdc-11e7-8225-0f6ed2ea93b8.png">

**Comment by RDPB2-Kuer** [comment]
OK
