### ISSUE TITLE
Prototype : ปรับแก้หน้าจอแปลงที่ดิน (Menu ย่อย)

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#39]
![image](https://user-images.githubusercontent.com/30930235/32500295-827394e8-c407-11e7-8643-3e39f5897c3d.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ

<img width="1196" alt="screen shot 2017-11-18 at 21 39 46" src="https://user-images.githubusercontent.com/23309321/32981478-073c3942-cca9-11e7-8756-c28accea4a04.png">

**Comment by RDPB2-Kuer** [comment]
OK
