### ISSUE TITLE
Prototype : ปรับปรุงหน้าจอ Dashboard เพิ่มการเปรียบเทียบภาพ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#40]
ให้สามารถแสดงเปรียบเทียบภาพแปลงที่ดิน และภาพแปลงที่ดินบนแผนที่ ที่จัดเก็บในแต่ละช่วงเวลา ดังภาพตัวอย่าง

![image](https://user-images.githubusercontent.com/30930235/32500613-6773da76-c408-11e7-89ca-dfc9917ce4d6.png)

**Comment by RDPB2-Kuer** [comment]
พี่ยังไม่แน่ใจว่าจะไปเปรียบเทียบตรงหัวข้อไหนดีค่ะ

**Comment by RDPB2-Kuer** [comment]
เราจะไปเพิ่มตรง tab รูปแปลงที่ดิน ดีไหมคะ โดยให้สามารถแสดงภาพต่างๆ ที่จัดเก็บ และมีปุ่มให้แสดงภาพที่ต้องการเปรียบเทียบด้วยนะคะ คือ ให้ user สามารถเลือกได้ว่าจะเปรียบเทียบภาพวันไหน กับวันไหน และจุดไหน ได้ด้วยนะคะ

**Comment by wannarukb** [comment]
คือเปรียบเทียบเป็นแปลงต่อแปลงใช่ไหมคะ  งั้นเล็กทำเป็นหน้าเรื่อง เปรียบเทียบแปลง โดยเป็นปุ่มมาจาก หน้ารายละเอียดแปลงที่ดิน

แปลงที่ดิน > เปรียบเทียบแปลง 
ให้เปรียบเทียบจาก 2 แปลง เป็นเป็นซ้ายขวา โดยสามารถเลือกภาพ เป็น Dropdown ที่บอกภาพ กับวันเวลา เอามาเทียบกัน แบบนี้ได้ไหมคะ
แต่เบื้องต้นคือ อาจจะเป็น ภาพ Mockup ก่อนค่ะ

**Comment by RDPB2-Kuer** [comment]
ได้เลยคะ

**Comment by RDPB2-Kuer** [comment]
พี่เห็นตัวอย่างการแสดงภาพในแต่ละช่วงเวลา เป็นแบบรูปด้านล่าง ดูทันสมัยดี ไม่ทราบว่าพอจะ apply ใช้กับของเราได้ไหมคะ
![image](https://user-images.githubusercontent.com/30930235/33417940-24008386-d5d6-11e7-80a6-2da916d9ddfe.png)

**Comment by wannarukb** [comment]
ตรงเลือกช่วงเวลาเล็กคิดว่าเป็นการเปรียบเทียบแค่เฉพาะแปลงที่ดินถูกต้องไหมคะ 
เล็กขออนุญาตวาง ปุ่มไว้ที่หน้าแปลงที่ดิน และกดมาเพื่อเปรียบเทียบนะคะ ถ้าในเชิงการใช้งานคือเปรียบเทียบเฉพาะวันเวลาถูกไหมคะ >_____< 

<img width="1209" alt="screen shot 2017-12-03 at 03 40 16" src="https://user-images.githubusercontent.com/23309321/33519558-b68bd302-d7db-11e7-9501-1b5729b5dfca.png">

**Comment by RDPB2-Kuer** [comment]
OK
