### ISSUE TITLE
Prototype : หน้าจอรายการสมาชิก - ปรับแก้การแสดงข้อมูลรายการ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#41]
![image](https://user-images.githubusercontent.com/30930235/32976461-afff3ffe-cc48-11e7-882c-10484dbb147f.png)

**Comment by RDPB2-Kuer** [comment]
![image](https://user-images.githubusercontent.com/30930235/32976471-09308ee8-cc49-11e7-8342-b436d238f09a.png)

**Comment by RDPB2-Kuer** [comment]
เนื่องจากเป็นหน้าแรกของระบบสมาชิก อยากให้น้องเล็กช่วยปรับให้น่าสนใจมากกว่านี้ ถ้าทำได้นะคะ

**Comment by wannarukb** [comment]
แก้เรียบร้อยแล้วค่ะ เดี๋ยวขออนุญาตรวมไว้ในอันนี้ทั้งหมดเลยนะคะ 
#28 
#29

**Comment by RDPB2-Kuer** [comment]
ขอถามหน่อยนะคะ อันนี้เป็นกรณีที่เลือกสมาชิกเป็นหลัก แล้วในกรณีที่เลือกแปลงที่ดินเป็นหลัก หน้าจอแสดงรายการจะเป็นรูปแบบไหนคะ

**Comment by RDPB2-Kuer** [comment]
ต้องขอทำความเข้าใจกันก่อนนะคะ สาเหตุที่พี่ออกแบบเป็น 2 ส่วน แบบนี้

1. กรณีเลือกปุ่ม "สมาชิกเครือข่าย" ที่ main menu เป็นการแสดงรายการ โดยใช้ชื่อสมาชิกเป็นหลัก 
   ดังนั้น รายละเอียดในหน้านี้จะเป็นข้อมูลบางส่วนของสมาชิก แต่จะให้สามารถดูแปลงที่ดินได้ เลยออกมาเป็นแบบนี้

![image](https://user-images.githubusercontent.com/30930235/33008347-5077da78-ce05-11e7-8581-3fde6b4defdd.png)
2. กรณีเลือกปุ่ม "แปลงที่ดิน" ที่ main menu เป็นการแสดงรายการ โดยใช้ชื่อแปลงที่ดินเป็นหลัก ดังนั้น รายละเอียด
    ดังนั้น ในหน้านี้จะเป็นข้อมูลบางส่วนของแปลงที่ดิน แต่จะให้สามารถดูสมาชิกได้ การแสดงข้อมูลก็จะสลับกันกับข้อ 1 
    คะ

**Comment by RDPB2-Kuer** [comment]
นอกจากนี้ การแสดงรายการสมาชิก กับรายการแปลงที่ดิน ก็จะเรียงลำดับต่างกันด้วยคะ

**Comment by RDPB2-Kuer** [comment]
ขอปรึกษาหน่อยคะ จากเหตุผลที่บอก เราจะปรับแก้การแสดงรายการสมาชิกเป็นแบบเดิม ดีไหมค่ะ คือ
![image](https://user-images.githubusercontent.com/30930235/33107881-ddbcbfd6-cf6b-11e7-95c9-4441b49ce267.png)
และใช้ภาพ default ตามภาพที่น้องเล็กใส่ไว้

**Comment by wannarukb** [comment]
สรุปคือ เล็กแก้ให้เป็นแบบเดิมนะคะ แต่ว่า ถ้าไม่สวยยังไง เดี๋ยวเล็กช่วยออกแบบอีกทีได้ค่ะ
1. ที่ Main menu เลือก "สมาชิกเครือข่าย", เลือก "ดูข้อมูลสมาชิก", เลือก "แปลงที่ดิน"
<img width="1170" alt="screen shot 2017-11-22 at 23 37 18" src="https://user-images.githubusercontent.com/23309321/33138916-54f45326-cfde-11e7-94f1-32e34bc37564.png">

2. ที่ Main menu เลือก "แดชบอร์ด", เลือก "ดูรายการแปลงที่ดิน"
3. ที่ Main menu เลือก "แปลงที่ดินสมาชิก"
<img width="1202" alt="screen shot 2017-11-22 at 23 52 23" src="https://user-images.githubusercontent.com/23309321/33139554-373b4f68-cfe0-11e7-8ed4-033653b1f450.png">

**Comment by RDPB2-Kuer** [comment]
OK
