### ISSUE TITLE
Prototype : หน้าจอข้อมูลสมาชิก - ปรับแก้กรณีสร้างข้อมูลใหม่

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#43]
![image](https://user-images.githubusercontent.com/30930235/32976579-1ffd34c0-cc4c-11e7-85dd-426effe2da44.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
<img width="1187" alt="screen shot 2017-11-23 at 00 08 42" src="https://user-images.githubusercontent.com/23309321/33140421-857daf84-cfe2-11e7-99d0-3ad7a59b1813.png">

**Comment by RDPB2-Kuer** [comment]
OK
