### ISSUE TITLE
Prototype : หน้าจอข้อมูลสมาชิก - ขอเปลี่ยนภาพ Background

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#44]
![image](https://user-images.githubusercontent.com/30930235/32976618-09d3e5f8-cc4d-11e7-8c07-fa762a6bc1f8.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะะ
<img width="1217" alt="screen shot 2017-11-18 at 17 05 05" src="https://user-images.githubusercontent.com/23309321/32979154-a68ca256-cc82-11e7-8baf-1c31bcf4d140.png">

**Comment by RDPB2-Kuer** [comment]
OK
