### ISSUE TITLE
Prototype : หน้าจอแผนที่ - ขอปรับขนาดการแสดงแผนที่

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#45]
![image](https://user-images.githubusercontent.com/30930235/32978684-c373015c-cc79-11e7-809e-f3733b80b914.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่า
<img width="1265" alt="screen shot 2017-11-18 at 18 41 59" src="https://user-images.githubusercontent.com/23309321/32979925-879bc2c4-cc90-11e7-8508-6852040d5002.png">

**Comment by RDPB2-Kuer** [comment]
OK
