### ISSUE TITLE
Prototype : หน้าจอแผนที่ - ปรับแก้ box แสดงข้อมูลแปลงที่ดิน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#46]
รบกวนน้องเล็กช่วยออกแบบ เพื่อให้น้องแผนที่แก้ไขคะ

![image](https://user-images.githubusercontent.com/30930235/32978728-842ccc16-cc7a-11e7-94b6-04550f138c64.png)

**Comment by wannarukb** [comment]
อันนี้คือให้เล็กทำเป็นรูปภาพตัวอย่างใช่ไหมคะ ??

**Comment by RDPB2-Kuer** [comment]
ใช่คะ

**Comment by wannarukb** [comment]
แบบนี้ได้ไหมคะ

![group 2](https://user-images.githubusercontent.com/23309321/33273219-344b4d2a-d3bf-11e7-89ac-a37731320de2.png)

**Comment by RDPB2-Kuer** [comment]
OK

**Comment by RDPB2-Kuer** [comment]
แนตคะ ช่วยประสานกับน้องโจ้ให้ปรับแก้ด้วยนะคะ

**Comment by RDPB2-Kuer** [comment]
พี่ลองส่งไปให้น้องที่เขียนส่วนของ map แล้วนะคะ รอเขาบอกว่าต้องการข้อมูลอะไรบ้าง ถ้าเปลี่ยน icon เป็นแบบนี้คะ แล้วจะแจ้งน้องเล็กอีกทีค่ะ

**Comment by RDPB2-Kuer** [comment]
ถามแล้วคะ เขาขอ file ของ icon นี้ น้องเล็กช่วยส่งให้หน่อยได้ไหมคะ

**Comment by wannarukb** [comment]
icon ค่ะะ 
[Icon.zip](https://github.com/cmmadnat/itok/files/1513992/Icon.zip)

**Comment by RDPB2-Kuer** [comment]
OK
