### ISSUE TITLE
Prototype : ปรับเพิ่มปุ่มบนหน้าจอแดชบอร์ด

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#47]
![image](https://user-images.githubusercontent.com/30930235/32979013-b559670e-cc7f-11e7-8480-e974a8efd930.png)

**Comment by RDPB2-Kuer** [comment]
สำหรับปุ่มที่ 1 และ 2 พี่จะไปนำเสนอลูกค้าให้ยืนยันก่อนนะคะ

**Comment by wannarukb** [comment]
เรียบร้อยค่า

<img width="1265" alt="screen shot 2017-11-18 at 18 41 59" src="https://user-images.githubusercontent.com/23309321/32979899-30618eda-cc90-11e7-9f61-8a436c722dd1.png">

**Comment by RDPB2-Kuer** [comment]
OK
