### ISSUE TITLE
Prototype : หน้าจอสมาชิก - ปรับปรุงหน้าจอสรุป

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#48]
![image](https://user-images.githubusercontent.com/30930235/32979590-867e4156-cc8a-11e7-9fa9-a428a6d50c27.png)

**Comment by wannarukb** [comment]
เนื่องจาก เกิดจากคำตกค่ะ เล็กขออนุญาตปรับตามภาพนี้นะคะ
<img width="760" alt="screen shot 2017-11-19 at 02 28 37" src="https://user-images.githubusercontent.com/23309321/32984068-8740d972-ccd1-11e7-8af7-17e7e8f35269.png">

**Comment by RDPB2-Kuer** [comment]
OK
