### ISSUE TITLE
Prototype : หน้าจอแปลงที่ดิน - ขอเพิ่มการออกแบบหน้าจอบันทึกโคกหนองนา

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#49]
ช่วยออกแบบการบันทึกข้อมูลโคกหนองนาให้ด้วยคะ
ซึ่งจะเป็นการบันทึกข้อมูลแบบ transaction คือ อาจมีการปรับปรุงข้อมูลในภายหลัง ซึ่งจะต้องจัดเก็บข้อมูลเดิมไว้ด้วย
และในการบันทึกข้อมูลนี้ ให้สามารถจัดเก็บภาพเกี่ยวกับการออกแบบโคกหนองนาด้วยนะคะ เช่น
![image](https://user-images.githubusercontent.com/30930235/32980764-40ff59a2-cc9f-11e7-95ac-06628d95ca10.png)

**Comment by RDPB2-Kuer** [comment]
![image](https://user-images.githubusercontent.com/30930235/32980796-c8c502ce-cc9f-11e7-8765-a4f98d45aadc.png)

**Comment by wannarukb** [comment]
แก้ไขเรียบร้อยแล้วค่ะ

**Comment by RDPB2-Kuer** [comment]
OK
