### ISSUE TITLE
DB : ขอเพิ่มชื่อแปลงที่ดิน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#5]
![image](https://user-images.githubusercontent.com/30930235/31064596-16667ab0-a768-11e7-9bf7-5e6413fbab79.png)

**Comment by cmmadnat** [comment]
![image](https://user-images.githubusercontent.com/37333/31072521-79a23964-a792-11e7-8c2d-c685bde9ede6.png)
