### ISSUE TITLE
Prototype : ตัวอย่างเอกสารสิทธิใส่ใน Prototype ได้

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#50]
![image](https://user-images.githubusercontent.com/30930235/32980847-896fd5b2-cca0-11e7-90af-f0f6a86b25c9.png)

**Comment by wannarukb** [comment]
ตัวนี้ให้ใส่ตรงไหนคะ แอบงงนิดหน่อยค่า

**Comment by RDPB2-Kuer** [comment]
![image](https://user-images.githubusercontent.com/30930235/33166778-114cb72c-d06e-11e7-8512-7fbdfe7e2ad0.png)

**Comment by RDPB2-Kuer** [comment]
ยกเลิก
