### ISSUE TITLE
Prototype : หน้า Dashboard - กรณีเลือกหัวข้อ "กราฟสรุปข้อมูลสมาชิก"

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#51]
ช่วยทำกราฟเป็นข้อมูลเบื้องต้น ดังนี้
1. จำนวนสมาชิกเครือข่าย แยกตามเพศ
2. จำนวนสมาชิกเครือข่าย ย้อนหลัง 5 ปี
3. จำนวนสมาชิกเครือข่าย แยกตามช่วงอายุ (ต่ำกว่า 20, 20-29, 30-39, 40-49, 50-59, 60 ขึ้นไป)
4. จำนวนสมาชิกเครือข่าย แยกตามรูปแบบเครือข่าย
5. จำนวนสมาชิกเครือข่ายสูงสุด 5 อันดับแรก แยกตามอาชีพหลัก

**Comment by wannarukb** [comment]
คำถามนิดนึงค่า อยากรบกวนคอนเฟิมอีกทีนึงค่ะ ว่าเล็กเข้าใจถูกไหม
เป็นจำนวน
- จำนวนสมาชิกเครือข่าย แยกตามเพศ => เป็นกราฟ บอก ชาย หญิง กับ จำนวนนะคะ หรือ เป็นจำนวนรูปภาพแค่สองอันไม่เป็น กราฟ
- จำนวนสมาชิกเครือข่าย ย้อนหลัง 5 ปี => อันนี้แสดงเป็นจำนวนนะคะ

เป็น Barchart
- จำนวนสมาชิกเครือข่าย แยกตามช่วงอายุ (ต่ำกว่า 20, 20-29, 30-39, 40-49, 50-59, 60 ขึ้นไป)=> อันนี้เล็กทำเป็น กราฟ Bar chart นะคะ
- จำนวนสมาชิกเครือข่าย แยกตามรูปแบบเครือข่าย => เป็นกราฟ barchart รูปแบบเครือข่าย กับ จำนวนนะคะ
- จำนวนสมาชิกเครือข่ายสูงสุด 5 อันดับแรก แยกตามอาชีพหลัก=> เป็นกราฟ barchart อาชีพ กับ จำนวนนะคะ

**Comment by RDPB2-Kuer** [comment]
คำตอบคะ:-
1. จำนวนสมาชิกเครือข่าย แยกตามเพศ => เป็นกราฟ บอก ชาย หญิง กับ จำนวนนะคะ หรือ เป็นจำนวนรูปภาพแค่สองอันไม่เป็น กราฟ **เป็นกราพวงกลม ดีไหมคะ**

2. จำนวนสมาชิกเครือข่าย ย้อนหลัง 5 ปี => อันนี้แสดงเป็นจำนวนนะคะเป็น Barchart **ได้ค่ะ**

3. จำนวนสมาชิกเครือข่าย แยกตามช่วงอายุ (ต่ำกว่า 20, 20-29, 30-39, 40-49, 50-59, 60 ขึ้นไป)=> อันนี้เล็กทำเป็น กราฟ Bar chart นะคะ **ได้ค่ะ**

4. จำนวนสมาชิกเครือข่าย แยกตามรูปแบบเครือข่าย => เป็นกราฟ barchart รูปแบบเครือข่าย กับ จำนวนนะคะ **เนื่องจากมี 2 รูปแบบเท่านั้น เป็นกราฟวงกลมดีไหมคะ**

5. จำนวนสมาชิกเครือข่ายสูงสุด 5 อันดับแรก แยกตามอาชีพหลัก=> เป็นกราฟ barchart อาชีพ กับ จำนวนนะคะ
**ใช่ค่ะ**

**Comment by RDPB2-Kuer** [comment]
อันนี้เป็นตัวอย่างที่น้องเคยทำแล้วนำเสนอให้ที่ ITOK เป็น power point ใช้ google นะคะ ลองดูเป็น idea นะคะ

![image](https://user-images.githubusercontent.com/30930235/33251483-784c2ae0-d369-11e7-9e92-2d99f157d2ac.png)

![image](https://user-images.githubusercontent.com/30930235/33251499-a7879074-d369-11e7-974e-e7c6aa9610a8.png)

![image](https://user-images.githubusercontent.com/30930235/33251519-cc17ab36-d369-11e7-855f-b5b814518316.png)

![image](https://user-images.githubusercontent.com/30930235/33251529-dc7829a6-d369-11e7-8d4f-b9214701e7d2.png)

![image](https://user-images.githubusercontent.com/30930235/33251536-eb3e1c7a-d369-11e7-949e-ae258937553d.png)

![image](https://user-images.githubusercontent.com/30930235/33251546-03621b76-d36a-11e7-93e7-855eedcc5b9f.png)

![image](https://user-images.githubusercontent.com/30930235/33251554-181bdd5e-d36a-11e7-8825-d663bc4307b1.png)

![image](https://user-images.githubusercontent.com/30930235/33251560-25bf6e26-d36a-11e7-9c46-77781928f52e.png)

**Comment by wannarukb** [comment]
เพิ่มให้เรียบร้อยแล้วค่ะ เป็นจำนวนกราฟ 5 กราฟ นะคะ
กด กราฟสรุปข้อมูลสมาชิก ปุ่มมาจาก หน้า Dashboard ถูกไหมคะ

<img width="1266" alt="screen shot 2017-11-29 at 03 00 48" src="https://user-images.githubusercontent.com/23309321/33341462-a873194c-d4b1-11e7-8d88-8998e74681e7.png">

**Comment by RDPB2-Kuer** [comment]
OK
