### ISSUE TITLE
Prototype : หน้าจอ Dashboard - กรณีเลือกหัวข้อ "กราฟสรุปแปลงที่ดิน"

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#52]
ขอทำกราฟตัวอย่างนำเสนอลูกค้า ดังนี้

1. จำนวนแปลงที่ดิน ย้อนหลัง 5 ปี
2. จำนวนแปลงที่ดินสูงสุด 5 จังหวัดแรก
3. จำนวนแปลงที่ดินสูงสุด 5 ลุ่มน้ำแรก

**Comment by wannarukb** [comment]
ขอทำกราฟตัวอย่างนำเสนอลูกค้า ดังนี้

- จำนวนแปลงที่ดิน ย้อนหลัง 5 ปี ( เป็นภาพแสดงจำนวนนะคะ​ )
- จำนวนแปลงที่ดินสูงสุด 5 จังหวัดแรก ( เป็น Bar chart ที่แสดง จำนวนที่ดิน กับ จังหวัดใช่ไหมคะ​​ )
- จำนวนแปลงที่ดินสูงสุด 5 ลุ่มน้ำแรก ( เป็น Bar chart ที่แสดง จำนวนที่ดิน กับ ลุ่มน้ำใช่ไหมคะ​​ )

**Comment by RDPB2-Kuer** [comment]
ใช่คะ

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ

<img width="1266" alt="screen shot 2017-11-29 at 03 09 13" src="https://user-images.githubusercontent.com/23309321/33341829-b8c9d8d4-d4b2-11e7-84bd-0d69c1136549.png">

**Comment by RDPB2-Kuer** [comment]
OK
