### ISSUE TITLE
Prototype : หน้าจอบันทึกฝึกอบรม และกิจกรรม - ช่วยออกแบบหน้าจอบันทึกข้อมูล

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#53]
น้องเล็กจะออกแบบส่วนของการบันทึกข้อมูลการจัดฝึกอบรม และการจัดกิจกรรมได้เลยไหมค่ะ ถ้าได้ก็จะดีมากค่ะ
ในการทำกิจกรรม อาจมีการฝึกอบรมพร้อมกันด้วย

**Comment by wannarukb** [comment]
ส่วนของการบันทึกข้อมูลการจัดฝึกอบรม และการจัดกิจกรรม
อันนี้เป็นในมุมมองของการ เพิ่มการจัดฝึกอบรม และการจัดกิจกรรมใช่ไหมคะ

**Comment by RDPB2-Kuer** [comment]
ใช่คะ

**Comment by wannarukb** [comment]
ขอ Merge นะคะ #74

**Comment by RDPB2-Kuer** [comment]
OK
