### ISSUE TITLE
Prototype : หน้าจอแปลงที่ดิน - เพิ่มการวางปุ่มเพื่อวาดรูปแปลงที่ดิน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#54]
ช่วยปรึกษากับแนตว่าจะวางปุ่ม "วาดรูปแปลงที่ดิน" ไว้ตรงส่วนไหนด้วยคะ

**Comment by RDPB2-Kuer** [comment]
ทำเป็นปุ่มก่อนก็พอคะ อยากให้ user ทราบว่ามี function นี้อยู่

**Comment by wannarukb** [comment]
ขออนุญาตใส่ไว้ตรงหน้าข้อมูลแปลงที่ดินนะคะ
<img width="1187" alt="screen shot 2017-11-22 at 22 52 13" src="https://user-images.githubusercontent.com/23309321/33136458-d17f4f74-cfd7-11e7-88c9-1332b3976435.png">

**Comment by RDPB2-Kuer** [comment]
OK
