### ISSUE TITLE
Prototype : หน้าจอ dashboard ปรับแก้ปุ่มที่เพิ่มยังไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#58]
![image](https://user-images.githubusercontent.com/30930235/33016672-04dd8848-ce22-11e7-8f08-513c9afdfdf3.png)

ปุ่มที่ 1 = กราฟสรุปข้อมูลสมาชิก จะไปที่หน้าแสดงกราฟสรุปข้อมูลสมาชิกที่ขอให้ทำเพิ่ม
ปุ่มที่ 2 = กราฟสรุปข้อมูลแปลงที่ดิน จะไปที่หน้าแสดงกราฟสรุปข้อมูลแปลงที่ดินที่ขอให้ทำเพิ่ม
ปุ่มที่ 3 = ดูรายการข้อมูลสมาชิก จะไปที่หน้าแสดงรายการข้อมูลสมาชิก
ปุ่มที่ 4= ดูรายการข้อมูลแปลงที่ดิน จะไปที่หน้าแสดงรายการข้อมูลแปลงที่ดิน

ช่วยทำ link ให้ด้วยคะ

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ 
<img width="1208" alt="screen shot 2017-11-22 at 22 07 52" src="https://user-images.githubusercontent.com/23309321/33134171-9cbcb75a-cfd1-11e7-827d-399500c431c6.png">

**Comment by RDPB2-Kuer** [comment]
OK
