### ISSUE TITLE
Prototype : หน้าจอข้อมูลแปลงที่ดิน - ปรับปรุงหน้ารายงานสรุป

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#61]
![image](https://user-images.githubusercontent.com/30930235/33164202-6356c846-d064-11e7-931f-d84e66ef8832.png)

**Comment by wannarukb** [comment]
อันนี้น่าจะเกิดจากการตกของคำเวลา เปิด main-menu ค่ะ
เล็กขอแก้ให้เป็นรูปแบบนี้นะคะ

<img width="1018" alt="screen shot 2017-11-26 at 02 06 18" src="https://user-images.githubusercontent.com/23309321/33233785-694e64e8-d24e-11e7-8435-cf66df2afdcf.png">

**Comment by RDPB2-Kuer** [comment]
OK
