### ISSUE TITLE
Prototype : ขอให้ออกแบบ Default รูปสมาชิก และแปลงที่ดิน เป็นรูปแบบเดียวกัน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#62]
ที่เคยบอกไว้ว่าจะขอให้ default รูปสมาชิก กับแปลงที่ดินเป็นแบบเดียวกัน คือ เป็นรูปภาพ หรือ Icon นะคะ

![image](https://user-images.githubusercontent.com/30930235/33166850-47b1acd2-d06e-11e7-9538-c8369a33e7d9.png)

![image](https://user-images.githubusercontent.com/30930235/33166894-61c46c54-d06e-11e7-901c-61023b67ff5d.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
<img width="395" alt="screen shot 2017-11-26 at 01 57 54" src="https://user-images.githubusercontent.com/23309321/33233741-4770530a-d24d-11e7-8548-b7f7b1455503.png">

**Comment by RDPB2-Kuer** [comment]
OK
