### ISSUE TITLE
Prototype : หน้าจอรายการแปลงที่ดิน - ปุ่มแสดงข้อมูลไม่ทำงาน และปรับปรุงการแสดงข้อมูล

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#63]
ที่ถูกต้องควรไปแสดงหน้าจอแสดงข้อมูลแปลงที่ดิน 
![image](https://user-images.githubusercontent.com/30930235/33170069-7f2e1aaa-d079-11e7-9515-622bdfa97a30.png)

**Comment by RDPB2-Kuer** [comment]
ขอเพิ่มตรงนี้ด้วยคะ
![image](https://user-images.githubusercontent.com/30930235/33173116-65f22ade-d085-11e7-8632-f112ad3b5c51.png)

**Comment by RDPB2-Kuer** [comment]
ปรับแก้เพิ่มเติมค่ะ
![image](https://user-images.githubusercontent.com/30930235/33173617-5ec478d2-d087-11e7-9ca5-2a9d169f90c8.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ
ตรงปุ่มที่อาจจะกดไม่ได้ ถ้ามาจากหน้าที่แสดง list เดี๋ยวส่งนี้เล็กพยายามปรึกษากับทางพี่แนทเพื่อแก้ไขค่ะ
ตอนแรกเป็นแค่ Mock up เฉยๆค่ะ ขอโทษด้วยค่ะ >_<
<img width="1187" alt="screen shot 2017-11-24 at 00 02 44" src="https://user-images.githubusercontent.com/23309321/33183556-e6808068-d0aa-11e7-93f7-7851d93440d4.png">

**Comment by RDPB2-Kuer** [comment]
OK
