### ISSUE TITLE
Prototype : หน้าจอแปลงที่ดิน - ข้อมูลแปลงที่ดิน เพิ่มตัวอย่างภาพ และลบปุ่ม

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#64]
ขอเตรียมข้อมูลตัวอย่างสำหรับการนำเสนอนะคะ

![image](https://user-images.githubusercontent.com/30930235/33171727-f919ca20-d07f-11e7-9fa6-eb7763feda9d.png)

ตัวอย่างสำเนาเอกสารสิทธิ
![default](https://user-images.githubusercontent.com/30930235/33171750-0cf83cd4-d080-11e7-818c-e8432ced4232.jpg)

ตัวอย่างขอบเขตที่ดิน
![default](https://user-images.githubusercontent.com/30930235/33171764-1b5cc150-d080-11e7-98a8-06e725ea7425.jpg)

**Comment by RDPB2-Kuer** [comment]
ขอย้ายปุ่มนี้ไปอยู่ในขั้นตอนการบันทึกข้อมูลแปลงที่ดิน จึงขอลบปุ่มนี้ออกก่อนคะ
![image](https://user-images.githubusercontent.com/30930235/33173686-a5bfc4c6-d087-11e7-8cd9-cf5c692ca6e2.png)

**Comment by RDPB2-Kuer** [comment]
ปรับแก้เพิ่มเติมค่ะ
![image](https://user-images.githubusercontent.com/30930235/33174361-51527386-d08a-11e7-944e-fdd536dc4ac0.png)

**Comment by RDPB2-Kuer** [comment]
ปรับแก้เพิ่มเติมอีกหน
![image](https://user-images.githubusercontent.com/30930235/33231046-dda48fbc-d220-11e7-934a-e49b0183a57b.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ

<img width="1265" alt="screen shot 2017-11-26 at 23 38 37" src="https://user-images.githubusercontent.com/23309321/33242160-fed8000a-d302-11e7-8c5c-a38cea8b9527.png">

**Comment by RDPB2-Kuer** [comment]
OK
