### ISSUE TITLE
Prototype : หน้าจอรายการสมาชิก - กดปุ่มดูข้อมูลสมาชิก แสดงหน้าจอไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#65]
เมื่อกดปุ่มดูข้อมูลสมาชิก ระบบแสดงรายการแปลงที่ดินก่อน ซึ่งไม่ถูกต้อง ควรไปแสดงรายละเอียดสมาชิกเลย
![screen shot 2560-11-23 at 19 59 19](https://user-images.githubusercontent.com/30930235/33174114-355d990e-d089-11e7-9556-82fd43266870.png)

**Comment by wannarukb** [comment]
แก้ไขเรียบร้อยแล้วค่ะ

**Comment by RDPB2-Kuer** [comment]
OK
