### ISSUE TITLE
Prototype : หน้าจอ Dashboard - การแสดงข้อมูลกรณีกดปุ่ม "ดูรายการสมาชิก"

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#66]
ขอแยกการแสดงข้อมูลสมาชิก กรณีกดปุ่ม "ดูรายการสมาชิก" ให้เป็นการแสดงข้อมูลอย่างเดียวเท่านั้น ปรับแก้หรือเพิ่มเติมข้อมูลไม่ได้ จึงต้องปรับปรุงการแสดงหน้าจอสำหรับการเลือก Dashboard ดังนี้

1. เมื่อกดปุ่ม "แดชบอร์ด" ที่ main menu
![image](https://user-images.githubusercontent.com/30930235/33174702-b4cdd68e-d08b-11e7-9896-f254e241a3ea.png)
2. เมื่อกดปุ่ม "ดูรายการสมาชิก"
![image](https://user-images.githubusercontent.com/30930235/33175393-456d3282-d08e-11e7-8312-6d84c5e619bd.png)
3. เมื่อกดปุ่ม "ดูข้อมูลสมาชิก"
![image](https://user-images.githubusercontent.com/30930235/33175496-908e63d0-d08e-11e7-812d-2c0f88451d3b.png)
ขอเพิ่มปุ่มกลับไปหน้าจอหลักของ dashboard ด้วย

**Comment by wannarukb** [comment]
อันนี้เล็กตัดออกตามภาพให้แล้วค่ะ เรื่องการ highlight เดี๋ยวปรึกษา back-end กับพี่แนทอีกทีค่ะ

**Comment by RDPB2-Kuer** [comment]
OK
