### ISSUE TITLE
Prototype : หน้าจอ Dashboard - การแสดงข้อมูลกรณีกดปุ่ม "ดูรายการแปลงที่ดิน"

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#67]
ขอแยกการแสดงข้อมูลสมาชิก กรณีกดปุ่ม "ดูรายการแปลง" ให้เป็นการแสดงข้อมูลอย่างเดียวเท่านั้น ปรับแก้หรือเพิ่มเติมข้อมูลไม่ได้ จึงต้องปรับปรุงการแสดงหน้าจอสำหรับการเลือก Dashboard ดังนี้

1. เมื่อกดปุ่ม "แดชบอร์ด" ที่ main menu
![image](https://user-images.githubusercontent.com/30930235/33174702-b4cdd68e-d08b-11e7-9896-f254e241a3ea.png)
2. เมื่อกดปุ่ม "ดูรายการแปลงที่ดิน"
![image](https://user-images.githubusercontent.com/30930235/33176071-573fedb8-d090-11e7-9834-9489ad95f6ac.png)
3. เมื่อกดปุ่ม "ดูข้อมูลแปลงที่ดิน"
![image](https://user-images.githubusercontent.com/30930235/33176213-daf57858-d090-11e7-9cdd-850a028285c3.png)

**Comment by wannarukb** [comment]
เรื่องการปรับปุ่มต่างๆ เล็กแก้เรียบร้อยแล้วค่ะ
เหลือการทำ  Highlight ค่ะ เดี๋ยวปรึกษากับพี่แนทแล้วแจ้งอีกทีค่ะ

**Comment by RDPB2-Kuer** [comment]
OK
