### ISSUE TITLE
Prototype : หน้าจอการเพิ่มสมาชิกเครือข่าย - ปรับปรุงการแสดงข้อมูล Tab และหัวข้อ

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#68]
![image](https://user-images.githubusercontent.com/30930235/33177574-b134fdd6-d095-11e7-933d-cbcfac2113f1.png)

![image](https://user-images.githubusercontent.com/30930235/33176438-a2c7bb2a-d091-11e7-80de-f60a73cd5132.png)

![image](https://user-images.githubusercontent.com/30930235/33177049-d6819b28-d093-11e7-8f50-3e8fea6f4c60.png)

**Comment by RDPB2-Kuer** [comment]
ในกรณีสร้างสมาชิกใหม่ ให้กรอกรายละเอียดในส่วนของ ข้อมูลส่วนบุคคล และข้อมูลการเป็นสมาชิก เท่านั้น จึงขอตัด
 tab "ที่ดิน" ออก และเมื่อกดปุ่ม  "บันทึก" แล้วจึงจะแสดงปุ่ม "เพิ่มข้อมูลแปลงที่ดิน" ให้ user สามารถเพิ่มข้อมูลแปลงที่ดินของสมาชิกที่เพิ่มใหม่ที่หน้าจอ "เพิ่ม - แปลงที่ดิน" 
![image](https://user-images.githubusercontent.com/30930235/33177668-0ad839b6-d096-11e7-922d-9f762c25c7fe.png)

**Comment by wannarukb** [comment]
แก้ไขเรียบร้อยแล้วค่ะ
<img width="1202" alt="screen shot 2017-11-26 at 02 32 18" src="https://user-images.githubusercontent.com/23309321/33234021-1452dff6-d252-11e7-96b1-1741849b0ee3.png">

<img width="1186" alt="screen shot 2017-11-26 at 02 32 13" src="https://user-images.githubusercontent.com/23309321/33234022-1d1412f4-d252-11e7-9725-a9459c61ba16.png">

**Comment by RDPB2-Kuer** [comment]
ขอปรับแก้เพิ่มเติม ดังนี้
![image](https://user-images.githubusercontent.com/30930235/33247026-87cb4814-d34d-11e7-83f6-92fca3df95bb.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ

<img width="1194" alt="screen shot 2017-11-27 at 22 53 47" src="https://user-images.githubusercontent.com/23309321/33275632-ddcb6a14-d3c5-11e7-96de-ca75b7ddea76.png">

**Comment by RDPB2-Kuer** [comment]
OK
