### ISSUE TITLE
Prototype : หน้าจอการเพิ่มแปลงที่ดิน - ออกแบบหน้าจอการกรอกข้อมูลแปลงที่ดิน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#69]
1. เมื่อกดปุ่ม "แปลงที่ดิน" บน main menu
![image](https://user-images.githubusercontent.com/30930235/33177967-00bb6150-d097-11e7-82a2-465da16647b5.png)
2. เมื่อกดปุ่ม "เพิ่มแปลงที่ดินใหม่" ให้ออกแบบหน้าจอบันทึกข้อมูลแปลงที่ดิน
![image](https://user-images.githubusercontent.com/30930235/33178639-74217b78-d099-11e7-9244-5dbd05186836.png)

หมายเหตุ :-
พี่อยากให้รูปแบบการเพิ่มแปลงที่ดินใหม่ เหมือนการเพิ่มสมาชิกใหม่ 
โดยมี Tab ของข้อมูลที่สามารถเพิ่มได้เหมือนการแสดงข้อมูลแปลงที่ดิน

**Comment by wannarukb** [comment]
อันนี้จะมีจาก
#67 
ให้ตัดปุ่ม สร้างแปลงที่ดินใหม่ 
อันนี้เล็กเข้าใจถูกไหมคะ
1. ถ้ามาจาก Dashboard ให้ตัดปุ่ม เพิ่มที่ดินใหม่ ออก
2 ถ้ามาจาก Main menu > แปลงที่ดินสมาชิก > ให้สามารถ เพิ่มที่ดินใหม่ได้

**Comment by RDPB2-Kuer** [comment]
ใช่คะ
1. ถ้ามาจาก dashboard จะไปดูข้อมูลสมาชิก และแปลงที่ดินได้ แต่เพิ่มเติมหรือปรับแก้ไม่ได้คะ
    ที่ main menu จะแสดงที่ dashboard ที่เดียวคะ
2. ถ้ามาจาก main menu > สมาชิกเครือข่าย > แปลงที่ดิน : สามารถเพิ่มเติมหรือปรับปรุงข้อมูลแปลงที่ดินได้คะ
3. ถ้ามาจาก main menu > แปลงที่ดินสมาชิก : สามารถเพิ่มเติมหรือปรับปรุงข้อมูลแปลงที่ดินได้คะ 

คือ พี่อยากให้ออกแบบให้สะดวกกับ user เนื่องจากการดูข้อมูลสมาชิกแล้วก็อยากดูหรือปรับแก้ข้อมูลแปลงที่ดินได้ ในขณะเดียวกันถ้าดูข้อมูลแปลงที่ดินแล้วก็อาจกลับไปดูหรือปรับแก้ข้อมูลสมาชิกได้นะคะ จะได้ไม่ต้องเลือกที่ main menu เท่านั้น  
และถ้ามาจาก main menu > แปลงที่ดินสมาชิก : ให้แสดงรายการสมาชิกที่เป็นเจ้าของแปลงที่ดิน เหมือนกับกรณีที่เราดูสมาชิกแล้ว กดที่ชื่อระบบจะแสดงรายการแปลงที่ดินออกมา ดีไหมคะ

**Comment by wannarukb** [comment]
แก้ไขแล้วค่ะ เรื่องเพิ่มหน้าสำหรับ เพิ่มแปลงที่ดินใหม่ http://localhost:8080/page/newLand

<img width="1185" alt="screen shot 2017-11-28 at 00 28 04" src="https://user-images.githubusercontent.com/23309321/33279967-131a39c2-d3d3-11e7-8ae2-5e2b6e7c255c.png">

**Comment by RDPB2-Kuer** [comment]
OK
