### ISSUE TITLE
Prototype : หน้าจอแปลงที่ดิน - ปรับปรุงหน้าจอการจัดการโคกหนองนา

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#70]
![image](https://user-images.githubusercontent.com/30930235/33179291-79bd150e-d09b-11e7-853a-fbf92d346e19.png)

![image](https://user-images.githubusercontent.com/30930235/33189697-ee460a0c-d0d7-11e7-922e-12bd58b31df5.png)

**Comment by wannarukb** [comment]
แก้ไขเรียบร้อยแล้วค่ะ
<img width="1162" alt="screen shot 2017-11-26 at 23 53 00" src="https://user-images.githubusercontent.com/23309321/33242286-f8b395ca-d304-11e7-8e2a-692f807cfe5f.png">

<img width="1185" alt="screen shot 2017-11-26 at 23 52 52" src="https://user-images.githubusercontent.com/23309321/33242343-f222036c-d305-11e7-9a8b-a2701110edf9.png">

**Comment by RDPB2-Kuer** [comment]
มีบางส่วนที่ยังไม่ถูกต้อง ดังนี้
![image](https://user-images.githubusercontent.com/30930235/33246824-fd21e91c-d34b-11e7-8097-ec9cebe489c5.png)
![image](https://user-images.githubusercontent.com/30930235/33246853-3e71bce4-d34c-11e7-937a-a99643967da4.png)

**Comment by wannarukb** [comment]
แก้ไขเรียบร้อยแล้วค่ะ

<img width="1144" alt="screen shot 2017-11-27 at 22 58 11" src="https://user-images.githubusercontent.com/23309321/33275889-7a10c220-d3c6-11e7-8539-41e9338d1d0c.png">

<img width="1174" alt="screen shot 2017-11-27 at 22 59 00" src="https://user-images.githubusercontent.com/23309321/33275922-958c2224-d3c6-11e7-9b5e-ad5394a7a9f1.png">

**Comment by RDPB2-Kuer** [comment]
OK
