### ISSUE TITLE
Prototype : หน้าจอแปลงที่ดิน - ใส่รูปการออกแบบในหัวข้อการจัดการโคกหนองนา

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#72]
ที่หน้าจอนี้
![image](https://user-images.githubusercontent.com/30930235/33189727-3e4b5304-d0d8-11e7-8e08-3cf9520d5511.png)

ขอให้มีตัวอย่างแสดงภาพที่จัดเก็บ มี 2 ภาพ คือ
1. ร่างการออกแบบโคกหนองนา 
![image](https://user-images.githubusercontent.com/30930235/32980796-c8c502ce-cc9f-11e7-8765-a4f98d45aadc.png)
2. ผลการออกแบบโคกหนองนา
![image](https://user-images.githubusercontent.com/30930235/32980764-40ff59a2-cc9f-11e7-95ac-06628d95ca10.png)

**Comment by wannarukb** [comment]
แก้ไขเรียบร้อยแล้วค่ะ

<img width="1195" alt="screen shot 2017-11-27 at 00 05 51" src="https://user-images.githubusercontent.com/23309321/33242382-c5a4922c-d306-11e7-9f3b-ea9d071f78b9.png">

**Comment by RDPB2-Kuer** [comment]
OK
