### ISSUE TITLE
Prototype : ช่วยเพิ่มหน้าจอ Login

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#73]
ช่วยส่ง url ที่เปิดหน้า login ให้ก่อนด้วยคะ

**Comment by wannarukb** [comment]
http://localhost:8080/page/login แต่ว่า น่าจะเปิดที่ file login.html เพื่อดูตัวอย่างก่อนเลยได้อ่าค่ะ น่าจะเห็นภาพมากกว่า เนื่องจากว่า เล็กทำเป็น Prototype เอาไว้แต่ยังไม่ได้ต่อเข้ากับระบบในรูปแบบของพี่แนทอ่าค่ะ เดี๋ยวอันนี้เล็กลองปรึกษากับทางพี่แนทก่อนว่ายังไงค่ะ

**Comment by wannarukb** [comment]
แก้ไขเรียบร้อยแล้วค่ะ
เข้าผ่าน http://localhost:8080/page/login ได้เลยค่ะ

<img width="1280" alt="screen shot 2017-11-27 at 23 07 27" src="https://user-images.githubusercontent.com/23309321/33276297-c58c6e42-d3c7-11e7-8427-9f7cc5fe0093.png">

**Comment by RDPB2-Kuer** [comment]
OK เลยคะ แต่เรียกไปแล้วไม่แสดงหน้านี้เลยคะ อาจเพราะแนตยังไม่ upload หรือเปล่าไม่รู้

**Comment by RDPB2-Kuer** [comment]
เรียกดูตาม link ที่ให้ ระบบแสดงหน้านี้นะคะ
![image](https://user-images.githubusercontent.com/30930235/33378135-79a277ee-d546-11e7-964c-7d33af326f51.png)

**Comment by wannarukb** [comment]
ลอง link นี้น่าจะได้ ตามภาพเลยค่ะ ตอนแรกเล็กเข้าใจว่า run บน localhost >___<

https://itok-project.appspot.com/page/login

**Comment by RDPB2-Kuer** [comment]
OK
