### ISSUE TITLE
สรุปหน้าที่เพิ่มค่ะ

### ISSUE THREAD

**Issue by wannarukb** [cmmadnat/itok#74]
หน้าที่เล็กต้องทำเพิ่ม มีดังนี้ ถูกต้องไหมคะ  >____<
[DONE] หน้าเพิ่มการฝึกอบรม
[DONE] หน้าเพิ่มกิจกรรม
[DONE] เพิ่มข้อมูลแปลงที่ดิน
[DONE] กราฟสรุปข้อมูลสมาชิก
[DONE] กราฟสรุปข้อมูลแปลงที่ดิน
6. เปรียบเทียบที่ดิน

**Comment by RDPB2-Kuer** [comment]
ใช่คะ

**Comment by wannarukb** [comment]
หน้ากิจกรรม
<img width="1190" alt="screen shot 2017-12-03 at 01 18 11" src="https://user-images.githubusercontent.com/23309321/33518467-e827cf06-d7c7-11e7-989a-c48c6cd7b80e.png">

<img width="1181" alt="screen shot 2017-12-03 at 02 05 11" src="https://user-images.githubusercontent.com/23309321/33518837-6d0eac7a-d7ce-11e7-9efc-7d48058d234d.png">


หลักสูตรอบรม
<img width="1187" alt="screen shot 2017-12-03 at 02 02 48" src="https://user-images.githubusercontent.com/23309321/33518805-1776b12c-d7ce-11e7-8ca8-886a27b21cc5.png">

<img width="1250" alt="screen shot 2017-12-03 at 02 14 30" src="https://user-images.githubusercontent.com/23309321/33518916-bf55f622-d7cf-11e7-8d3a-87ac5a630ce2.png">

**Comment by wannarukb** [comment]
หน้ากิจกรรม
<img width="1194" alt="screen shot 2017-12-03 at 02 15 19" src="https://user-images.githubusercontent.com/23309321/33518925-d79ee446-d7cf-11e7-926d-f7795ed5aefe.png">


<img width="1181" alt="screen shot 2017-12-03 at 02 05 11" src="https://user-images.githubusercontent.com/23309321/33518837-6d0eac7a-d7ce-11e7-9efc-7d48058d234d.png">

<img width="1278" alt="screen shot 2017-12-03 at 02 25 45" src="https://user-images.githubusercontent.com/23309321/33519041-4f948608-d7d1-11e7-94d2-38589241cb15.png">

**Comment by RDPB2-Kuer** [comment]
OK
