### ISSUE TITLE
Prototype : หน้าแสดงรายการแปลงที่ดิน ขอปรับชื่อปุ่ม

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#77]
![image](https://user-images.githubusercontent.com/30930235/33247820-7b77e576-d353-11e7-9368-a195b1a05721.png)

**Comment by wannarukb** [comment]
แก้ไขแล้วค่า

<img width="1143" alt="screen shot 2017-11-27 at 23 20 45" src="https://user-images.githubusercontent.com/23309321/33276940-a1c111aa-d3c9-11e7-8d20-d2a1d7fbb7c7.png">

**Comment by RDPB2-Kuer** [comment]
OK
