### ISSUE TITLE
Prototype : หน้ารายการสมาชิก - ปรับแก้การแสดงชื่อจังหวัด

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#80]
![image](https://user-images.githubusercontent.com/30930235/33411856-79bd3d4e-d5ba-11e7-8cbf-4219543817f4.png)

**Comment by wannarukb** [comment]
เรียบร้อยค่ะ


<img width="634" alt="screen shot 2017-12-02 at 20 53 27" src="https://user-images.githubusercontent.com/23309321/33516294-085472d6-d7a3-11e7-957c-7c0f0b8a5f37.png">

**Comment by RDPB2-Kuer** [comment]
OK
