### ISSUE TITLE
Prototype : หน้ารายการสมาชิก - ปรับแก้รายการแปลงที่ดิน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#81]
![image](https://user-images.githubusercontent.com/30930235/33412239-b9886f3c-d5bc-11e7-9fce-bf8bd677e36b.png)
ให้สอดคล้องกันกับหน้านี้
![image](https://user-images.githubusercontent.com/30930235/33412397-9eb4463a-d5bd-11e7-95d5-c6a1464995ea.png)

**Comment by wannarukb** [comment]
ตรงส่วนนี้คือ ตรงชื่อ สมชาย ใจดี ใช่ไหมคะ ที่ต้องเปลี่ยนให้สอดคล้องกับ ศศิกาญจน์มณี โพธิ์ตะมี 
เล็กเข้าใจถูกไหมคะ

**Comment by RDPB2-Kuer** [comment]
ใช่คะ 
![image](https://user-images.githubusercontent.com/30930235/33548848-2fd0d4b6-d91b-11e7-8996-b25e5029a1a2.png)

**Comment by RDPB2-Kuer** [comment]
OK
