### ISSUE TITLE
Prototype : หน้าสมาชิก - ขอปรับแก้หน้ารายงานสรุป

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#83]
![image](https://user-images.githubusercontent.com/30930235/33418191-4a325646-d5d7-11e7-8fca-b69e38d6d553.png)

**Comment by wannarukb** [comment]
แก้ไขเรียบร้อยแล้วค่ะ

<img width="376" alt="screen shot 2017-12-02 at 21 01 46" src="https://user-images.githubusercontent.com/23309321/33516346-0b7b7896-d7a4-11e7-9fbd-e4b00bc40a8b.png">

**Comment by RDPB2-Kuer** [comment]
OK
