### ISSUE TITLE
Prototype : แปลงที่ดิน - กดปุ่มดูรายละเอียดแปลงที่ดิน แต่ระบบแสดงหน้าจอไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#84]
กดปุ่มนี้ที่หน้าจอแสดงรายการแปลงที่ดิน
![image](https://user-images.githubusercontent.com/30930235/33418238-88676898-d5d7-11e7-94c1-08ff1662b445.png)

ระบบแสดงหน้าจอไม่ถูกต้อง ดังนี้
![image](https://user-images.githubusercontent.com/30930235/33418304-d938ee86-d5d7-11e7-8738-a3b2178d0c38.png)

ที่ถูกต้องควรแสดงหน้าด้านล่างนี้
![image](https://user-images.githubusercontent.com/30930235/33418366-1a5eacf2-d5d8-11e7-9819-82018fc50c97.png)

**Comment by wannarukb** [comment]
แก้ไขแล้วค่ะ

**Comment by RDPB2-Kuer** [comment]
OK
