### ISSUE TITLE
Prototype : แปลงที่ดิน - กดปุ่มยกเลิกในข้อมูลการจัดการพื้นที่โคกหนองนา ระบบหยุดนิ่ง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#85]
![image](https://user-images.githubusercontent.com/30930235/33418434-65c8aa9e-d5d8-11e7-8643-4c0a5e266322.png)

**Comment by wannarukb** [comment]
แก้ไขเรียบร้อยแล้วค่ะ

**Comment by RDPB2-Kuer** [comment]
OK
