### ISSUE TITLE
Prototype : Dashboard - ลบปุ่มการแก้ไขข้อมูลแปลงที่ดิน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#86]
ที่หน้า dashboard > ดูรายการแปลงที่ดิน > ดูรายละเอียดแปลงที่ดิน

![image](https://user-images.githubusercontent.com/30930235/33418921-be2d594e-d5da-11e7-8936-774a021c044b.png)

**Comment by RDPB2-Kuer** [comment]
โดยสรุป การเลือกดูข้อมูลผ่านแดชบอร์ด จะต้องไม่ให้เพิ่มหรือแก้ไขข้อมูล จะเป็นการแสดงข้อมูลอย่างเดียว

**Comment by wannarukb** [comment]
แก้ไขเรียบร้อยแล้วค่ะ

**Comment by RDPB2-Kuer** [comment]
OK
