### ISSUE TITLE
Prototype : Dashboard - เมื่อกดปุ่มเลือกดูรายการสมาชิก ระบบ Highlight ที่ main menu ไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#87]
กรณีเลือก Dashboard 
![image](https://user-images.githubusercontent.com/30930235/33419011-286ed512-d5db-11e7-8a78-46f6d16d4a26.png)

เมื่อเลือก ดูรายการสมาชิก ระบบ highlight ที่ function สมาชิกเครือข่าย บน main menu ซึ่งไม่ถูกต้อง
![image](https://user-images.githubusercontent.com/30930235/33419110-86e9e154-d5db-11e7-81c1-4bb7597fe1be.png)
และเมื่อเลือก ดูข้อมูลสมาชิก ระบบ ระบบ highlight ที่ function สมาชิกเครือข่าย บน main menu ซึ่งไม่ถูกต้อง
![image](https://user-images.githubusercontent.com/30930235/33419150-bede941a-d5db-11e7-817d-d7e850485717.png)

**Comment by RDPB2-Kuer** [comment]
และกรณีเลือก Tab แปลงที่ดิน ต้องไม่มีปุ่มเพิ่มรายการ และ highlight ที่ แดชบอร์ด
![image](https://user-images.githubusercontent.com/30930235/33419256-326bd960-d5dc-11e7-8cd7-059cf401171b.png)

และเมื่อเลือก ดูข้อมูลแปลงที่ดิน ต้องไม่มีปุ่มแก้ไขข้อมูลแปลงที่ดิน
![image](https://user-images.githubusercontent.com/30930235/33419335-81f5ff10-d5dc-11e7-82a3-1ccaa841ba4f.png)

**Comment by wannarukb** [comment]
แก้ไขเรียบร้อยแล้วค่ะ

**Comment by RDPB2-Kuer** [comment]
OK
