### ISSUE TITLE
Prototype : Dashboard - ขอปุ่มกลับหน้าหลัก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#88]
![image](https://user-images.githubusercontent.com/30930235/33419418-d95b48fa-d5dc-11e7-9b46-1d3128947c89.png)

![image](https://user-images.githubusercontent.com/30930235/33419455-0ce090a4-d5dd-11e7-9d40-a75471ff9716.png)

**Comment by wannarukb** [comment]
เพิ่มเรียบร้อยแล้วค่ะ

<img width="1190" alt="screen shot 2017-12-02 at 22 27 18" src="https://user-images.githubusercontent.com/23309321/33517072-fe91d498-d7af-11e7-9b25-e9f81937a350.png">

**Comment by RDPB2-Kuer** [comment]
OK
