### ISSUE TITLE
Prototype : สมาชิกเครือข่าย  - ต้องมีปุ่มสำหรับแก้ไขด้วย

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#89]
![image](https://user-images.githubusercontent.com/30930235/33419551-85e7ce68-d5dd-11e7-84df-c6988f2892aa.png)

![image](https://user-images.githubusercontent.com/30930235/33419606-bb47ea5c-d5dd-11e7-8d89-cceb375c3b70.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ

**Comment by RDPB2-Kuer** [comment]
OK
