### ISSUE TITLE
Web : ยกเลิกการแสดง รหัสสมาชิก (ในหน้า สร้าง - สมาชิกเครือข่าย )

### ISSUE THREAD

**Issue by Srikridsadaporn** [cmmadnat/itok#9]
น้องแนตคะ
รบกวน ยกเลิกการแสดง รหัสสมาชิก ด้วยนะคะ

![Uploading image.png…]()

**Comment by cmmadnat** [comment]
ผมเอาออกให้ก่อนละกันนะครับ แต่ต่อไปน่าจะได้ใช้
