### ISSUE TITLE
Prototype : ขอคำปรึกษาตัวอย่างหน้า Login

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#90]
แบบนี้สวยไหมคะ
![image](https://user-images.githubusercontent.com/30930235/33471872-e7929584-d6a1-11e7-8bae-a332e0507c48.png)

**Comment by wannarukb** [comment]
แบบนี้ก็ได้ค่ะ เล็กว่าดีทั้งสองแบบเลย ทั้งแบบเดิม และ แบบใหม่ แต่อาจจะกล่องตรงกลางก็ได้เหมือนกันค่ะ

**Comment by RDPB2-Kuer** [comment]
งั้นเอาแบบเดิมไปก่อน ถ้าน้องเล็กไม่เห็นว่าสวยกว่า

**Comment by RDPB2-Kuer** [comment]
OK
