### ISSUE TITLE
Prototype : Dashboard - ขอตัดคำว่า "กราฟ" ออก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#93]
![image](https://user-images.githubusercontent.com/30930235/33547483-c50d7976-d916-11e7-9d54-6ee6ab00b733.png)

![image](https://user-images.githubusercontent.com/30930235/33547546-f7ed350c-d916-11e7-9df7-ee430b1bdb0c.png)

![image](https://user-images.githubusercontent.com/30930235/33547679-7427cf6a-d917-11e7-9e01-b920ac85746d.png)

**Comment by wannarukb** [comment]
แก้เรียบร้อยแล้วค่ะ

**Comment by RDPB2-Kuer** [comment]
OK
