### ISSUE TITLE
Prototype : Dashboard  - เพิ่มปุ่มกลับ Dashboard ที่หน้าข้อมูลสมาชิก

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#95]
![image](https://user-images.githubusercontent.com/30930235/33548259-3aacc6c6-d919-11e7-980b-34cce0a07f47.png)

**Comment by wannarukb** [comment]
แก้ไขเรียบร้อยแล้วค่า

<img width="1178" alt="screen shot 2017-12-04 at 18 34 41" src="https://user-images.githubusercontent.com/23309321/33550814-d8dc15a6-d921-11e7-954b-13c808a3e1c2.png">

**Comment by RDPB2-Kuer** [comment]
OK
