### ISSUE TITLE
Prototype : Dashboard - ลบปุ่ม เส้นขอบเขตแปลงที่ดิน ที่หน้าข้อมูลแปลงที่ดิน

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#96]
![image](https://user-images.githubusercontent.com/30930235/33548401-a2275a0a-d919-11e7-9cde-5994c1df7d60.png)

**Comment by wannarukb** [comment]
เรียบร้อยแล้วค่ะ

<img width="1263" alt="screen shot 2017-12-04 at 18 36 29" src="https://user-images.githubusercontent.com/23309321/33550883-16afce72-d922-11e7-95d5-cb85f147c15e.png">

**Comment by RDPB2-Kuer** [comment]
OK
