### ISSUE TITLE
Prototype :  แปลงที่ดิน - หน้าจอการเปรียบเทียบยังไม่ถูกต้อง

### ISSUE THREAD

**Issue by RDPB2-Kuer** [cmmadnat/itok#97]
![image](https://user-images.githubusercontent.com/30930235/33550404-583b9a4e-d920-11e7-9fdf-81b044b57574.png)

**Comment by wannarukb** [comment]
แก้แล้วค่ะ เป็นแบบนี้นะคะ

<img width="1260" alt="screen shot 2017-12-04 at 18 42 56" src="https://user-images.githubusercontent.com/23309321/33551148-fedcf832-d922-11e7-9fbe-4a009a398616.png">

**Comment by RDPB2-Kuer** [comment]
OK
